<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />


<meta name="author" content="Yuwei Ma, Rachel Lu, Chenxi Liu, Xiuhong Fan, Daisy Gui" />


<title>Analysis &amp; Code</title>

<script src="site_libs/header-attrs-2.29/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/cerulean.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<link href="site_libs/font-awesome-6.5.2/css/all.min.css" rel="stylesheet" />
<link href="site_libs/font-awesome-6.5.2/css/v4-shims.min.css" rel="stylesheet" />

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>









<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">P8105 Final Project</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Diabetes Risk Prediction</a>
</li>
<li>
  <a href="Final_Project_Report.html">Final Project Report</a>
</li>
<li>
  <a href="Analysis_and_code.html">Analysis &amp; Code</a>
</li>
<li>
  <a href="Screencast.html">Screencast</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="https://github.com/Yuwei-Ma/p8105-diabetes.github.io">
    <span class="fa fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Analysis &amp; Code</h1>
<h4 class="author">Yuwei Ma, Rachel Lu, Chenxi Liu, Xiuhong Fan, Daisy
Gui</h4>
<h4 class="date">December 2025</h4>

</div>


<div id="p8105-final-project-diabetes-health-indicators"
class="section level1">
<h1>P8105 Final Project: Diabetes Health Indicators</h1>
<p><strong>Task 1: Data Cleaning, Variable Processing, and Train/Test
Dataset Creation</strong></p>
<p>Dataset: CDC BRFSS 2015 Diabetes Health Indicators<br />
Source: <a
href="https://www.kaggle.com/datasets/alexteboul/diabetes-health-indicators-dataset"
class="uri">https://www.kaggle.com/datasets/alexteboul/diabetes-health-indicators-dataset</a></p>
<div id="load-required-libraries" class="section level2">
<h2>Load Required Libraries</h2>
<pre class="r"><code>library(tidyverse)
library(caret)
library(skimr)
library(janitor)
library(corrplot)
library(DataExplorer)
library(knitr)
library(pROC)
# Set seed for reproducibility
set.seed(123)</code></pre>
</div>
<div id="data-import" class="section level2">
<h2>1. Data Import</h2>
<p>The dataset has three versions: -
<code>diabetes_012_health_indicators_BRFSS2015.csv</code> (3 classes: 0,
1, 2) -
<code>diabetes_binary_5050split_health_indicators_BRFSS2015.csv</code>
(balanced binary) -
<code>diabetes_binary_health_indicators_BRFSS2015.csv</code> (full
binary)</p>
<p>For this project, we’ll use the full binary version for more
data.</p>
<pre class="r"><code>diabetes_raw &lt;- read_csv(&quot;data/diabetes_binary_health_indicators_BRFSS2015.csv&quot;)

glimpse(diabetes_raw)</code></pre>
<pre><code>## Rows: 253,680
## Columns: 22
## $ Diabetes_binary      &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0…
## $ HighBP               &lt;dbl&gt; 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1…
## $ HighChol             &lt;dbl&gt; 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1…
## $ CholCheck            &lt;dbl&gt; 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1…
## $ BMI                  &lt;dbl&gt; 40, 25, 28, 27, 24, 25, 30, 25, 30, 24, 25, 34, 2…
## $ Smoker               &lt;dbl&gt; 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0…
## $ Stroke               &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0…
## $ HeartDiseaseorAttack &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0…
## $ PhysActivity         &lt;dbl&gt; 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1…
## $ Fruits               &lt;dbl&gt; 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1…
## $ Veggies              &lt;dbl&gt; 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1…
## $ HvyAlcoholConsump    &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…
## $ AnyHealthcare        &lt;dbl&gt; 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1…
## $ NoDocbcCost          &lt;dbl&gt; 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0…
## $ GenHlth              &lt;dbl&gt; 5, 3, 5, 2, 2, 2, 3, 3, 5, 2, 3, 3, 3, 4, 4, 2, 3…
## $ MentHlth             &lt;dbl&gt; 18, 0, 30, 0, 3, 0, 0, 0, 30, 0, 0, 0, 0, 0, 30, …
## $ PhysHlth             &lt;dbl&gt; 15, 0, 30, 0, 0, 2, 14, 0, 30, 0, 0, 30, 15, 0, 2…
## $ DiffWalk             &lt;dbl&gt; 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0…
## $ Sex                  &lt;dbl&gt; 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0…
## $ Age                  &lt;dbl&gt; 9, 7, 9, 11, 11, 10, 9, 11, 9, 8, 13, 10, 7, 11, …
## $ Education            &lt;dbl&gt; 4, 6, 4, 3, 5, 6, 6, 4, 5, 4, 6, 5, 5, 4, 6, 6, 4…
## $ Income               &lt;dbl&gt; 3, 1, 8, 6, 4, 8, 7, 4, 1, 3, 8, 1, 7, 6, 2, 8, 3…</code></pre>
</div>
<div id="initial-data-exploration" class="section level2">
<h2>2. Initial Data Exploration</h2>
<pre class="r"><code># Check for missing values
colSums(is.na(diabetes_raw))</code></pre>
<pre><code>##      Diabetes_binary               HighBP             HighChol 
##                    0                    0                    0 
##            CholCheck                  BMI               Smoker 
##                    0                    0                    0 
##               Stroke HeartDiseaseorAttack         PhysActivity 
##                    0                    0                    0 
##               Fruits              Veggies    HvyAlcoholConsump 
##                    0                    0                    0 
##        AnyHealthcare          NoDocbcCost              GenHlth 
##                    0                    0                    0 
##             MentHlth             PhysHlth             DiffWalk 
##                    0                    0                    0 
##                  Sex                  Age            Education 
##                    0                    0                    0 
##               Income 
##                    0</code></pre>
<pre class="r"><code># Summary statistics
summary(diabetes_raw)</code></pre>
<pre><code>##  Diabetes_binary      HighBP         HighChol        CholCheck     
##  Min.   :0.0000   Min.   :0.000   Min.   :0.0000   Min.   :0.0000  
##  1st Qu.:0.0000   1st Qu.:0.000   1st Qu.:0.0000   1st Qu.:1.0000  
##  Median :0.0000   Median :0.000   Median :0.0000   Median :1.0000  
##  Mean   :0.1393   Mean   :0.429   Mean   :0.4241   Mean   :0.9627  
##  3rd Qu.:0.0000   3rd Qu.:1.000   3rd Qu.:1.0000   3rd Qu.:1.0000  
##  Max.   :1.0000   Max.   :1.000   Max.   :1.0000   Max.   :1.0000  
##       BMI            Smoker           Stroke        HeartDiseaseorAttack
##  Min.   :12.00   Min.   :0.0000   Min.   :0.00000   Min.   :0.00000     
##  1st Qu.:24.00   1st Qu.:0.0000   1st Qu.:0.00000   1st Qu.:0.00000     
##  Median :27.00   Median :0.0000   Median :0.00000   Median :0.00000     
##  Mean   :28.38   Mean   :0.4432   Mean   :0.04057   Mean   :0.09419     
##  3rd Qu.:31.00   3rd Qu.:1.0000   3rd Qu.:0.00000   3rd Qu.:0.00000     
##  Max.   :98.00   Max.   :1.0000   Max.   :1.00000   Max.   :1.00000     
##   PhysActivity        Fruits          Veggies       HvyAlcoholConsump
##  Min.   :0.0000   Min.   :0.0000   Min.   :0.0000   Min.   :0.0000   
##  1st Qu.:1.0000   1st Qu.:0.0000   1st Qu.:1.0000   1st Qu.:0.0000   
##  Median :1.0000   Median :1.0000   Median :1.0000   Median :0.0000   
##  Mean   :0.7565   Mean   :0.6343   Mean   :0.8114   Mean   :0.0562   
##  3rd Qu.:1.0000   3rd Qu.:1.0000   3rd Qu.:1.0000   3rd Qu.:0.0000   
##  Max.   :1.0000   Max.   :1.0000   Max.   :1.0000   Max.   :1.0000   
##  AnyHealthcare     NoDocbcCost         GenHlth         MentHlth     
##  Min.   :0.0000   Min.   :0.00000   Min.   :1.000   Min.   : 0.000  
##  1st Qu.:1.0000   1st Qu.:0.00000   1st Qu.:2.000   1st Qu.: 0.000  
##  Median :1.0000   Median :0.00000   Median :2.000   Median : 0.000  
##  Mean   :0.9511   Mean   :0.08418   Mean   :2.511   Mean   : 3.185  
##  3rd Qu.:1.0000   3rd Qu.:0.00000   3rd Qu.:3.000   3rd Qu.: 2.000  
##  Max.   :1.0000   Max.   :1.00000   Max.   :5.000   Max.   :30.000  
##     PhysHlth         DiffWalk           Sex              Age        
##  Min.   : 0.000   Min.   :0.0000   Min.   :0.0000   Min.   : 1.000  
##  1st Qu.: 0.000   1st Qu.:0.0000   1st Qu.:0.0000   1st Qu.: 6.000  
##  Median : 0.000   Median :0.0000   Median :0.0000   Median : 8.000  
##  Mean   : 4.242   Mean   :0.1682   Mean   :0.4403   Mean   : 8.032  
##  3rd Qu.: 3.000   3rd Qu.:0.0000   3rd Qu.:1.0000   3rd Qu.:10.000  
##  Max.   :30.000   Max.   :1.0000   Max.   :1.0000   Max.   :13.000  
##    Education        Income     
##  Min.   :1.00   Min.   :1.000  
##  1st Qu.:4.00   1st Qu.:5.000  
##  Median :5.00   Median :7.000  
##  Mean   :5.05   Mean   :6.054  
##  3rd Qu.:6.00   3rd Qu.:8.000  
##  Max.   :6.00   Max.   :8.000</code></pre>
<pre class="r"><code># Check for duplicates
sum(duplicated(diabetes_raw))</code></pre>
<pre><code>## [1] 24206</code></pre>
<pre class="r"><code># Examine outcome variable distribution
table(diabetes_raw$Diabetes_binary)</code></pre>
<pre><code>## 
##      0      1 
## 218334  35346</code></pre>
<pre class="r"><code>prop.table(table(diabetes_raw$Diabetes_binary))</code></pre>
<pre><code>## 
##        0        1 
## 0.860667 0.139333</code></pre>
</div>
<div id="data-cleaning" class="section level2">
<h2>3. Data Cleaning</h2>
<pre class="r"><code>diabetes_clean &lt;- diabetes_raw %&gt;%
  # Clean column names
  clean_names() %&gt;%
  
  # Fix the heart disease variable name
  rename(heart_disease_or_attack = heart_diseaseor_attack) %&gt;%
  
  # Remove duplicates if any
  distinct() %&gt;%
  
  # Remove rows with missing values (if any)
  drop_na()

glimpse(diabetes_clean)</code></pre>
<pre><code>## Rows: 229,474
## Columns: 22
## $ diabetes_binary         &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0…
## $ high_bp                 &lt;dbl&gt; 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1…
## $ high_chol               &lt;dbl&gt; 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0…
## $ chol_check              &lt;dbl&gt; 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1…
## $ bmi                     &lt;dbl&gt; 40, 25, 28, 27, 24, 25, 30, 25, 30, 24, 25, 34…
## $ smoker                  &lt;dbl&gt; 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0…
## $ stroke                  &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0…
## $ heart_disease_or_attack &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0…
## $ phys_activity           &lt;dbl&gt; 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1…
## $ fruits                  &lt;dbl&gt; 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0…
## $ veggies                 &lt;dbl&gt; 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0…
## $ hvy_alcohol_consump     &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…
## $ any_healthcare          &lt;dbl&gt; 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1…
## $ no_docbc_cost           &lt;dbl&gt; 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0…
## $ gen_hlth                &lt;dbl&gt; 5, 3, 5, 2, 2, 2, 3, 3, 5, 2, 3, 3, 3, 4, 4, 2…
## $ ment_hlth               &lt;dbl&gt; 18, 0, 30, 0, 3, 0, 0, 0, 30, 0, 0, 0, 0, 0, 3…
## $ phys_hlth               &lt;dbl&gt; 15, 0, 30, 0, 0, 2, 14, 0, 30, 0, 0, 30, 15, 0…
## $ diff_walk               &lt;dbl&gt; 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0…
## $ sex                     &lt;dbl&gt; 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0…
## $ age                     &lt;dbl&gt; 9, 7, 9, 11, 11, 10, 9, 11, 9, 8, 13, 10, 7, 1…
## $ education               &lt;dbl&gt; 4, 6, 4, 3, 5, 6, 6, 4, 5, 4, 6, 5, 5, 4, 6, 6…
## $ income                  &lt;dbl&gt; 3, 1, 8, 6, 4, 8, 7, 4, 1, 3, 8, 1, 7, 6, 2, 8…</code></pre>
</div>
<div id="variable-processing-and-feature-engineering"
class="section level2">
<h2>4. Variable Processing and Feature Engineering</h2>
<div id="variable-descriptions" class="section level3">
<h3>Variable Descriptions</h3>
<p>According to the dataset documentation:</p>
<ol style="list-style-type: decimal">
<li><strong>Diabetes_binary</strong>: 0 = no diabetes, 1 = prediabetes
or diabetes</li>
<li><strong>HighBP</strong>: 0 = no, 1 = yes</li>
<li><strong>HighChol</strong>: 0 = no, 1 = yes</li>
<li><strong>CholCheck</strong>: 0 = no, 1 = yes (cholesterol check in 5
years)</li>
<li><strong>BMI</strong>: Body Mass Index</li>
<li><strong>Smoker</strong>: 0 = no, 1 = yes</li>
<li><strong>Stroke</strong>: 0 = no, 1 = yes</li>
<li><strong>HeartDiseaseorAttack</strong>: 0 = no, 1 = yes</li>
<li><strong>PhysActivity</strong>: 0 = no, 1 = yes</li>
<li><strong>Fruits</strong>: 0 = no, 1 = yes (consume fruit 1+ times per
day)</li>
<li><strong>Veggies</strong>: 0 = no, 1 = yes (consume vegetables 1+
times per day)</li>
<li><strong>HvyAlcoholConsump</strong>: 0 = no, 1 = yes</li>
<li><strong>AnyHealthcare</strong>: 0 = no, 1 = yes</li>
<li><strong>NoDocbcCost</strong>: 0 = no, 1 = yes (couldn’t see doctor
due to cost)</li>
<li><strong>GenHlth</strong>: 1-5 scale (1 = excellent, 5 = poor)</li>
<li><strong>MentHlth</strong>: days of poor mental health in past 30
days (0-30)</li>
<li><strong>PhysHlth</strong>: days of poor physical health in past 30
days (0-30)</li>
<li><strong>DiffWalk</strong>: 0 = no, 1 = yes (difficulty walking or
climbing stairs)</li>
<li><strong>Sex</strong>: 0 = female, 1 = male</li>
<li><strong>Age</strong>: 1-13 (age categories)</li>
<li><strong>Education</strong>: 1-6 (education level)</li>
<li><strong>Income</strong>: 1-8 (income categories)</li>
</ol>
</div>
<div id="processing" class="section level3">
<h3>Processing</h3>
<pre class="r"><code>diabetes_processed &lt;- diabetes_clean %&gt;%
  mutate(
    # Convert outcome to factor
    diabetes_binary = factor(diabetes_binary, 
                             levels = c(0, 1),
                             labels = c(&quot;No Diabetes&quot;, &quot;Diabetes&quot;)),
    
    # Convert binary variables to factors
    high_bp = factor(high_bp, levels = c(0, 1), labels = c(&quot;No&quot;, &quot;Yes&quot;)),
    high_chol = factor(high_chol, levels = c(0, 1), labels = c(&quot;No&quot;, &quot;Yes&quot;)),
    chol_check = factor(chol_check, levels = c(0, 1), labels = c(&quot;No&quot;, &quot;Yes&quot;)),
    smoker = factor(smoker, levels = c(0, 1), labels = c(&quot;No&quot;, &quot;Yes&quot;)),
    stroke = factor(stroke, levels = c(0, 1), labels = c(&quot;No&quot;, &quot;Yes&quot;)),
    heart_disease_or_attack = factor(heart_disease_or_attack, 
                                     levels = c(0, 1), 
                                     labels = c(&quot;No&quot;, &quot;Yes&quot;)),
    phys_activity = factor(phys_activity, levels = c(0, 1), labels = c(&quot;No&quot;, &quot;Yes&quot;)),
    fruits = factor(fruits, levels = c(0, 1), labels = c(&quot;No&quot;, &quot;Yes&quot;)),
    veggies = factor(veggies, levels = c(0, 1), labels = c(&quot;No&quot;, &quot;Yes&quot;)),
    hvy_alcohol_consump = factor(hvy_alcohol_consump, 
                                 levels = c(0, 1), 
                                 labels = c(&quot;No&quot;, &quot;Yes&quot;)),
    any_healthcare = factor(any_healthcare, levels = c(0, 1), labels = c(&quot;No&quot;, &quot;Yes&quot;)),
    no_docbc_cost = factor(no_docbc_cost, levels = c(0, 1), labels = c(&quot;No&quot;, &quot;Yes&quot;)),
    diff_walk = factor(diff_walk, levels = c(0, 1), labels = c(&quot;No&quot;, &quot;Yes&quot;)),
    sex = factor(sex, levels = c(0, 1), labels = c(&quot;Female&quot;, &quot;Male&quot;)),
    
    # Convert ordinal variables to factors
    gen_hlth_cat = factor(gen_hlth, 
                          levels = 1:5,
                          labels = c(&quot;Excellent&quot;, &quot;Very Good&quot;, &quot;Good&quot;, &quot;Fair&quot;, &quot;Poor&quot;),
                          ordered = TRUE),
    
    # Create age groups
    age_cat = factor(age,
                     levels = 1:13,
                     labels = c(&quot;18-24&quot;, &quot;25-29&quot;, &quot;30-34&quot;, &quot;35-39&quot;, &quot;40-44&quot;,
                                &quot;45-49&quot;, &quot;50-54&quot;, &quot;55-59&quot;, &quot;60-64&quot;, &quot;65-69&quot;,
                                &quot;70-74&quot;, &quot;75-79&quot;, &quot;80+&quot;),
                     ordered = TRUE),
    
    # Create education categories
    education_cat = factor(education,
                           levels = 1:6,
                           labels = c(&quot;Never/K-8&quot;, &quot;Grades 9-11&quot;, &quot;Grade 12/GED&quot;,
                                      &quot;College 1-3 yrs&quot;, &quot;College 4+ yrs&quot;, &quot;Unknown&quot;),
                           ordered = TRUE),
    
    # Create income categories
    income_cat = factor(income,
                        levels = 1:8,
                        labels = c(&quot;&lt;$10k&quot;, &quot;$10k-$15k&quot;, &quot;$15k-$20k&quot;, &quot;$20k-$25k&quot;,
                                   &quot;$25k-$35k&quot;, &quot;$35k-$50k&quot;, &quot;$50k-$75k&quot;, &quot;$75k+&quot;),
                        ordered = TRUE),
    
    # Create BMI categories
    bmi_category = case_when(
      bmi &lt; 18.5 ~ &quot;Underweight&quot;,
      bmi &gt;= 18.5 &amp; bmi &lt; 25 ~ &quot;Normal&quot;,
      bmi &gt;= 25 &amp; bmi &lt; 30 ~ &quot;Overweight&quot;,
      bmi &gt;= 30 ~ &quot;Obese&quot;
    ) %&gt;% factor(levels = c(&quot;Underweight&quot;, &quot;Normal&quot;, &quot;Overweight&quot;, &quot;Obese&quot;),
                 ordered = TRUE),
    
    # Create mental health categories
    ment_hlth_cat = case_when(
      ment_hlth == 0 ~ &quot;None&quot;,
      ment_hlth &lt;= 7 ~ &quot;1-7 days&quot;,
      ment_hlth &lt;= 14 ~ &quot;8-14 days&quot;,
      ment_hlth &lt;= 30 ~ &quot;15-30 days&quot;
    ) %&gt;% factor(levels = c(&quot;None&quot;, &quot;1-7 days&quot;, &quot;8-14 days&quot;, &quot;15-30 days&quot;),
                 ordered = TRUE),
    
    # Create physical health categories
    phys_hlth_cat = case_when(
      phys_hlth == 0 ~ &quot;None&quot;,
      phys_hlth &lt;= 7 ~ &quot;1-7 days&quot;,
      phys_hlth &lt;= 14 ~ &quot;8-14 days&quot;,
      phys_hlth &lt;= 30 ~ &quot;15-30 days&quot;
    ) %&gt;% factor(levels = c(&quot;None&quot;, &quot;1-7 days&quot;, &quot;8-14 days&quot;, &quot;15-30 days&quot;),
                 ordered = TRUE),
    
    # Create composite health score
    health_risk_score = as.numeric(high_bp == &quot;Yes&quot;) +
      as.numeric(high_chol == &quot;Yes&quot;) +
      as.numeric(stroke == &quot;Yes&quot;) +
      as.numeric(heart_disease_or_attack == &quot;Yes&quot;) +
      as.numeric(smoker == &quot;Yes&quot;) +
      as.numeric(hvy_alcohol_consump == &quot;Yes&quot;) +
      (gen_hlth - 1) / 4,
    
    # Create healthy lifestyle score
    lifestyle_score = as.numeric(phys_activity == &quot;Yes&quot;) +
      as.numeric(fruits == &quot;Yes&quot;) +
      as.numeric(veggies == &quot;Yes&quot;)
  )

glimpse(diabetes_processed)</code></pre>
<pre><code>## Rows: 229,474
## Columns: 31
## $ diabetes_binary         &lt;fct&gt; No Diabetes, No Diabetes, No Diabetes, No Diab…
## $ high_bp                 &lt;fct&gt; Yes, No, Yes, Yes, Yes, Yes, Yes, Yes, Yes, No…
## $ high_chol               &lt;fct&gt; Yes, No, Yes, No, Yes, Yes, No, Yes, Yes, No, …
## $ chol_check              &lt;fct&gt; Yes, No, Yes, Yes, Yes, Yes, Yes, Yes, Yes, Ye…
## $ bmi                     &lt;dbl&gt; 40, 25, 28, 27, 24, 25, 30, 25, 30, 24, 25, 34…
## $ smoker                  &lt;fct&gt; Yes, Yes, No, No, No, Yes, Yes, Yes, Yes, No, …
## $ stroke                  &lt;fct&gt; No, No, No, No, No, No, No, No, No, No, No, No…
## $ heart_disease_or_attack &lt;fct&gt; No, No, No, No, No, No, No, No, Yes, No, No, N…
## $ phys_activity           &lt;fct&gt; No, Yes, No, Yes, Yes, Yes, No, Yes, No, No, Y…
## $ fruits                  &lt;fct&gt; No, No, Yes, Yes, Yes, Yes, No, No, Yes, No, Y…
## $ veggies                 &lt;fct&gt; Yes, No, No, Yes, Yes, Yes, No, Yes, Yes, Yes,…
## $ hvy_alcohol_consump     &lt;fct&gt; No, No, No, No, No, No, No, No, No, No, No, No…
## $ any_healthcare          &lt;fct&gt; Yes, No, Yes, Yes, Yes, Yes, Yes, Yes, Yes, Ye…
## $ no_docbc_cost           &lt;fct&gt; No, Yes, Yes, No, No, No, No, No, No, No, No, …
## $ gen_hlth                &lt;dbl&gt; 5, 3, 5, 2, 2, 2, 3, 3, 5, 2, 3, 3, 3, 4, 4, 2…
## $ ment_hlth               &lt;dbl&gt; 18, 0, 30, 0, 3, 0, 0, 0, 30, 0, 0, 0, 0, 0, 3…
## $ phys_hlth               &lt;dbl&gt; 15, 0, 30, 0, 0, 2, 14, 0, 30, 0, 0, 30, 15, 0…
## $ diff_walk               &lt;fct&gt; Yes, No, Yes, No, No, No, No, Yes, Yes, No, No…
## $ sex                     &lt;fct&gt; Female, Female, Female, Female, Female, Male, …
## $ age                     &lt;dbl&gt; 9, 7, 9, 11, 11, 10, 9, 11, 9, 8, 13, 10, 7, 1…
## $ education               &lt;dbl&gt; 4, 6, 4, 3, 5, 6, 6, 4, 5, 4, 6, 5, 5, 4, 6, 6…
## $ income                  &lt;dbl&gt; 3, 1, 8, 6, 4, 8, 7, 4, 1, 3, 8, 1, 7, 6, 2, 8…
## $ gen_hlth_cat            &lt;ord&gt; Poor, Good, Poor, Very Good, Very Good, Very G…
## $ age_cat                 &lt;ord&gt; 60-64, 50-54, 60-64, 70-74, 70-74, 65-69, 60-6…
## $ education_cat           &lt;ord&gt; College 1-3 yrs, Unknown, College 1-3 yrs, Gra…
## $ income_cat              &lt;ord&gt; $15k-$20k, &lt;$10k, $75k+, $35k-$50k, $20k-$25k,…
## $ bmi_category            &lt;ord&gt; Obese, Overweight, Overweight, Overweight, Nor…
## $ ment_hlth_cat           &lt;ord&gt; 15-30 days, None, 15-30 days, None, 1-7 days, …
## $ phys_hlth_cat           &lt;ord&gt; 15-30 days, None, 15-30 days, None, None, 1-7 …
## $ health_risk_score       &lt;dbl&gt; 4.00, 1.50, 3.00, 1.25, 2.25, 3.25, 2.50, 3.50…
## $ lifestyle_score         &lt;dbl&gt; 1, 1, 1, 3, 3, 3, 0, 2, 2, 1, 3, 2, 1, 1, 2, 1…</code></pre>
</div>
</div>
<div id="data-quality-checks" class="section level2">
<h2>5. Data Quality Checks</h2>
<pre class="r"><code># Check for any issues in processed data
sum(is.na(diabetes_processed))</code></pre>
<pre><code>## [1] 0</code></pre>
<pre class="r"><code># Verify factor levels
table(diabetes_processed$diabetes_binary)</code></pre>
<pre><code>## 
## No Diabetes    Diabetes 
##      194377       35097</code></pre>
<pre class="r"><code># Check continuous variables for outliers
diabetes_processed %&gt;%
  select(bmi, ment_hlth, phys_hlth, health_risk_score, lifestyle_score) %&gt;%
  summary()</code></pre>
<pre><code>##       bmi          ment_hlth       phys_hlth      health_risk_score
##  Min.   :12.00   Min.   : 0.00   Min.   : 0.000   Min.   :0.000    
##  1st Qu.:24.00   1st Qu.: 0.00   1st Qu.: 0.000   1st Qu.:1.000    
##  Median :27.00   Median : 0.00   Median : 0.000   Median :1.750    
##  Mean   :28.69   Mean   : 3.51   Mean   : 4.681   Mean   :1.971    
##  3rd Qu.:32.00   3rd Qu.: 2.00   3rd Qu.: 4.000   3rd Qu.:2.750    
##  Max.   :98.00   Max.   :30.00   Max.   :30.000   Max.   :7.000    
##  lifestyle_score
##  Min.   :0.00   
##  1st Qu.:2.00   
##  Median :2.00   
##  Mean   :2.14   
##  3rd Qu.:3.00   
##  Max.   :3.00</code></pre>
</div>
<div id="traintest-split" class="section level2">
<h2>6. Train/Test Split</h2>
<p>Create stratified train/test split (80/20) using stratified sampling
to maintain outcome distribution.</p>
<pre class="r"><code># Set seed again for reproducibility
set.seed(123)

# Create partition index
train_index &lt;- createDataPartition(
  diabetes_processed$diabetes_binary,
  p = 0.80,
  list = FALSE,
  times = 1
)

# Create training and testing datasets
diabetes_train &lt;- diabetes_processed[train_index, ]
diabetes_test &lt;- diabetes_processed[-train_index, ]

# Verify split proportions
nrow(diabetes_train)</code></pre>
<pre><code>## [1] 183580</code></pre>
<pre class="r"><code>nrow(diabetes_test)</code></pre>
<pre><code>## [1] 45894</code></pre>
<pre class="r"><code># Check outcome distribution in train and test sets
prop.table(table(diabetes_train$diabetes_binary))</code></pre>
<pre><code>## 
## No Diabetes    Diabetes 
##   0.8470531   0.1529469</code></pre>
<pre class="r"><code>prop.table(table(diabetes_test$diabetes_binary))</code></pre>
<pre><code>## 
## No Diabetes    Diabetes 
##   0.8470606   0.1529394</code></pre>
</div>
<div id="export-cleaned-datasets" class="section level2">
<h2>7. Export Cleaned Datasets</h2>
<pre class="r"><code># Create output directory if it doesn&#39;t exist
if (!dir.exists(&quot;data&quot;)) {
  dir.create(&quot;data&quot;)
}

# Save processed datasets
write_csv(diabetes_processed, &quot;data/diabetes_processed.csv&quot;)
write_csv(diabetes_train, &quot;data/diabetes_train.csv&quot;)
write_csv(diabetes_test, &quot;data/diabetes_test.csv&quot;)

# Also save as RDS for faster loading in R
saveRDS(diabetes_processed, &quot;data/diabetes_processed.rds&quot;)
saveRDS(diabetes_train, &quot;data/diabetes_train.rds&quot;)
saveRDS(diabetes_test, &quot;data/diabetes_test.rds&quot;)</code></pre>
</div>
<div id="data-dictionary-and-variable-summary" class="section level2">
<h2>8. Data Dictionary and Variable Summary</h2>
<pre class="r"><code># Create and save data dictionary
data_dictionary &lt;- tribble(
  ~Variable, ~Type, ~Description, ~Values,
  &quot;diabetes_binary&quot;, &quot;Factor&quot;, &quot;Diabetes diagnosis&quot;, &quot;No_Diabetes, Diabetes&quot;,
  &quot;high_bp&quot;, &quot;Factor&quot;, &quot;High blood pressure&quot;, &quot;No, Yes&quot;,
  &quot;high_chol&quot;, &quot;Factor&quot;, &quot;High cholesterol&quot;, &quot;No, Yes&quot;,
  &quot;chol_check&quot;, &quot;Factor&quot;, &quot;Cholesterol check in past 5 years&quot;, &quot;No, Yes&quot;,
  &quot;bmi&quot;, &quot;Numeric&quot;, &quot;Body Mass Index&quot;, &quot;Continuous&quot;,
  &quot;smoker&quot;, &quot;Factor&quot;, &quot;Smoked at least 100 cigarettes in life&quot;, &quot;No, Yes&quot;,
  &quot;stroke&quot;, &quot;Factor&quot;, &quot;History of stroke&quot;, &quot;No, Yes&quot;,
  &quot;heart_disease_or_attack&quot;, &quot;Factor&quot;, &quot;Coronary heart disease or MI&quot;, &quot;No, Yes&quot;,
  &quot;phys_activity&quot;, &quot;Factor&quot;, &quot;Physical activity in past 30 days&quot;, &quot;No, Yes&quot;,
  &quot;fruits&quot;, &quot;Factor&quot;, &quot;Consume fruit 1+ times per day&quot;, &quot;No, Yes&quot;,
  &quot;veggies&quot;, &quot;Factor&quot;, &quot;Consume vegetables 1+ times per day&quot;, &quot;No, Yes&quot;,
  &quot;hvy_alcohol_consump&quot;, &quot;Factor&quot;, &quot;Heavy alcohol consumption&quot;, &quot;No, Yes&quot;,
  &quot;any_healthcare&quot;, &quot;Factor&quot;, &quot;Have any healthcare coverage&quot;, &quot;No, Yes&quot;,
  &quot;no_docbc_cost&quot;, &quot;Factor&quot;, &quot;Could not see doctor due to cost&quot;, &quot;No, Yes&quot;,
  &quot;gen_hlth&quot;, &quot;Numeric&quot;, &quot;General health rating&quot;, &quot;1-5 (1=excellent, 5=poor)&quot;,
  &quot;ment_hlth&quot;, &quot;Numeric&quot;, &quot;Days of poor mental health (past 30)&quot;, &quot;0-30&quot;,
  &quot;phys_hlth&quot;, &quot;Numeric&quot;, &quot;Days of poor physical health (past 30)&quot;, &quot;0-30&quot;,
  &quot;diff_walk&quot;, &quot;Factor&quot;, &quot;Difficulty walking or climbing stairs&quot;, &quot;No, Yes&quot;,
  &quot;sex&quot;, &quot;Factor&quot;, &quot;Biological sex&quot;, &quot;Female, Male&quot;,
  &quot;age&quot;, &quot;Numeric&quot;, &quot;Age category&quot;, &quot;1-13 (see age_cat for labels)&quot;,
  &quot;education&quot;, &quot;Numeric&quot;, &quot;Education level&quot;, &quot;1-6&quot;,
  &quot;income&quot;, &quot;Numeric&quot;, &quot;Income level&quot;, &quot;1-8&quot;,
  &quot;bmi_category&quot;, &quot;Factor&quot;, &quot;BMI category&quot;, &quot;Underweight, Normal, Overweight, Obese&quot;,
  &quot;health_risk_score&quot;, &quot;Numeric&quot;, &quot;Composite health risk score&quot;, &quot;Continuous (0-7)&quot;,
  &quot;lifestyle_score&quot;, &quot;Numeric&quot;, &quot;Healthy lifestyle score&quot;, &quot;0-3&quot;
)

write_csv(data_dictionary, &quot;data/data_dictionary.csv&quot;)</code></pre>
<pre class="r"><code># Create comprehensive variable summary table organized by category
variables_summary &lt;- tibble(
  Category = c(
    &quot;Outcome&quot;,
    &quot;Health Conditions&quot;, &quot;Health Conditions&quot;, &quot;Health Conditions&quot;, &quot;Health Conditions&quot;, &quot;Health Conditions&quot;,
    &quot;Physical Metrics&quot;, &quot;Physical Metrics&quot;, &quot;Physical Metrics&quot;,
    &quot;Lifestyle&quot;, &quot;Lifestyle&quot;, &quot;Lifestyle&quot;, &quot;Lifestyle&quot;, &quot;Lifestyle&quot;,
    &quot;Health Status&quot;, &quot;Health Status&quot;, &quot;Health Status&quot;, &quot;Health Status&quot;, &quot;Health Status&quot;,
    &quot;Healthcare Access&quot;, &quot;Healthcare Access&quot;,
    &quot;Demographics&quot;, &quot;Demographics&quot;, &quot;Demographics&quot;, &quot;Demographics&quot;, &quot;Demographics&quot;, &quot;Demographics&quot;, &quot;Demographics&quot;,
    &quot;Engineered Features&quot;, &quot;Engineered Features&quot;
  ),
  Variable = c(
    &quot;diabetes_binary&quot;,
    &quot;high_bp&quot;, &quot;high_chol&quot;, &quot;stroke&quot;, &quot;heart_disease_or_attack&quot;, &quot;chol_check&quot;,
    &quot;bmi&quot;, &quot;bmi_category&quot;, &quot;diff_walk&quot;,
    &quot;smoker&quot;, &quot;phys_activity&quot;, &quot;fruits&quot;, &quot;veggies&quot;, &quot;hvy_alcohol_consump&quot;,
    &quot;gen_hlth&quot;, &quot;ment_hlth&quot;, &quot;phys_hlth&quot;, &quot;ment_hlth_cat&quot;, &quot;phys_hlth_cat&quot;,
    &quot;any_healthcare&quot;, &quot;no_docbc_cost&quot;,
    &quot;age&quot;, &quot;age_cat&quot;, &quot;sex&quot;, &quot;education&quot;, &quot;education_cat&quot;, &quot;income&quot;, &quot;income_cat&quot;,
    &quot;health_risk_score&quot;, &quot;lifestyle_score&quot;
  ),
  Description = c(
    &quot;No_Diabetes, Diabetes&quot;,
    &quot;High blood pressure (No, Yes)&quot;, &quot;High cholesterol (No, Yes)&quot;, &quot;History of stroke (No, Yes)&quot;, 
    &quot;History of heart disease or attack (No, Yes)&quot;, &quot;Cholesterol check in past 5 years (No, Yes)&quot;,
    &quot;Body Mass Index (continuous)&quot;, &quot;Underweight, Normal, Overweight, Obese&quot;, &quot;Difficulty walking/climbing stairs (No, Yes)&quot;,
    &quot;Smoked 100+ cigarettes lifetime (No, Yes)&quot;, &quot;Physical activity past 30 days (No, Yes)&quot;, 
    &quot;Consume fruit 1+ times/day (No, Yes)&quot;, &quot;Consume vegetables 1+ times/day (No, Yes)&quot;, &quot;Heavy alcohol consumption (No, Yes)&quot;,
    &quot;General health (1-5: Excellent to Poor)&quot;, &quot;Days poor mental health past 30 days (0-30)&quot;, 
    &quot;Days poor physical health past 30 days (0-30)&quot;, &quot;Mental health categories (None, 1-7, 8-14, 15-30 days)&quot;, 
    &quot;Physical health categories (None, 1-7, 8-14, 15-30 days)&quot;,
    &quot;Has healthcare coverage (No, Yes)&quot;, &quot;Could not see doctor due to cost (No, Yes)&quot;,
    &quot;Age category (1-13)&quot;, &quot;Age groups (18-24, 25-29, ..., 80+)&quot;, &quot;Biological sex (Female, Male)&quot;, 
    &quot;Education level (1-6)&quot;, &quot;Education categories&quot;, &quot;Income level (1-8)&quot;, &quot;Income categories (&lt;$10k, ..., $75k+)&quot;,
    &quot;Composite health risk score (0-7)&quot;, &quot;Healthy lifestyle score (0-3)&quot;
  )
)

kable(variables_summary, caption = &quot;Dataset Variables by Category&quot;)</code></pre>
<table>
<caption>Dataset Variables by Category</caption>
<colgroup>
<col width="19%" />
<col width="23%" />
<col width="56%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">Category</th>
<th align="left">Variable</th>
<th align="left">Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Outcome</td>
<td align="left">diabetes_binary</td>
<td align="left">No_Diabetes, Diabetes</td>
</tr>
<tr class="even">
<td align="left">Health Conditions</td>
<td align="left">high_bp</td>
<td align="left">High blood pressure (No, Yes)</td>
</tr>
<tr class="odd">
<td align="left">Health Conditions</td>
<td align="left">high_chol</td>
<td align="left">High cholesterol (No, Yes)</td>
</tr>
<tr class="even">
<td align="left">Health Conditions</td>
<td align="left">stroke</td>
<td align="left">History of stroke (No, Yes)</td>
</tr>
<tr class="odd">
<td align="left">Health Conditions</td>
<td align="left">heart_disease_or_attack</td>
<td align="left">History of heart disease or attack (No, Yes)</td>
</tr>
<tr class="even">
<td align="left">Health Conditions</td>
<td align="left">chol_check</td>
<td align="left">Cholesterol check in past 5 years (No, Yes)</td>
</tr>
<tr class="odd">
<td align="left">Physical Metrics</td>
<td align="left">bmi</td>
<td align="left">Body Mass Index (continuous)</td>
</tr>
<tr class="even">
<td align="left">Physical Metrics</td>
<td align="left">bmi_category</td>
<td align="left">Underweight, Normal, Overweight, Obese</td>
</tr>
<tr class="odd">
<td align="left">Physical Metrics</td>
<td align="left">diff_walk</td>
<td align="left">Difficulty walking/climbing stairs (No, Yes)</td>
</tr>
<tr class="even">
<td align="left">Lifestyle</td>
<td align="left">smoker</td>
<td align="left">Smoked 100+ cigarettes lifetime (No, Yes)</td>
</tr>
<tr class="odd">
<td align="left">Lifestyle</td>
<td align="left">phys_activity</td>
<td align="left">Physical activity past 30 days (No, Yes)</td>
</tr>
<tr class="even">
<td align="left">Lifestyle</td>
<td align="left">fruits</td>
<td align="left">Consume fruit 1+ times/day (No, Yes)</td>
</tr>
<tr class="odd">
<td align="left">Lifestyle</td>
<td align="left">veggies</td>
<td align="left">Consume vegetables 1+ times/day (No, Yes)</td>
</tr>
<tr class="even">
<td align="left">Lifestyle</td>
<td align="left">hvy_alcohol_consump</td>
<td align="left">Heavy alcohol consumption (No, Yes)</td>
</tr>
<tr class="odd">
<td align="left">Health Status</td>
<td align="left">gen_hlth</td>
<td align="left">General health (1-5: Excellent to Poor)</td>
</tr>
<tr class="even">
<td align="left">Health Status</td>
<td align="left">ment_hlth</td>
<td align="left">Days poor mental health past 30 days (0-30)</td>
</tr>
<tr class="odd">
<td align="left">Health Status</td>
<td align="left">phys_hlth</td>
<td align="left">Days poor physical health past 30 days (0-30)</td>
</tr>
<tr class="even">
<td align="left">Health Status</td>
<td align="left">ment_hlth_cat</td>
<td align="left">Mental health categories (None, 1-7, 8-14, 15-30
days)</td>
</tr>
<tr class="odd">
<td align="left">Health Status</td>
<td align="left">phys_hlth_cat</td>
<td align="left">Physical health categories (None, 1-7, 8-14, 15-30
days)</td>
</tr>
<tr class="even">
<td align="left">Healthcare Access</td>
<td align="left">any_healthcare</td>
<td align="left">Has healthcare coverage (No, Yes)</td>
</tr>
<tr class="odd">
<td align="left">Healthcare Access</td>
<td align="left">no_docbc_cost</td>
<td align="left">Could not see doctor due to cost (No, Yes)</td>
</tr>
<tr class="even">
<td align="left">Demographics</td>
<td align="left">age</td>
<td align="left">Age category (1-13)</td>
</tr>
<tr class="odd">
<td align="left">Demographics</td>
<td align="left">age_cat</td>
<td align="left">Age groups (18-24, 25-29, …, 80+)</td>
</tr>
<tr class="even">
<td align="left">Demographics</td>
<td align="left">sex</td>
<td align="left">Biological sex (Female, Male)</td>
</tr>
<tr class="odd">
<td align="left">Demographics</td>
<td align="left">education</td>
<td align="left">Education level (1-6)</td>
</tr>
<tr class="even">
<td align="left">Demographics</td>
<td align="left">education_cat</td>
<td align="left">Education categories</td>
</tr>
<tr class="odd">
<td align="left">Demographics</td>
<td align="left">income</td>
<td align="left">Income level (1-8)</td>
</tr>
<tr class="even">
<td align="left">Demographics</td>
<td align="left">income_cat</td>
<td align="left">Income categories (&lt;$10k, …, $75k+)</td>
</tr>
<tr class="odd">
<td align="left">Engineered Features</td>
<td align="left">health_risk_score</td>
<td align="left">Composite health risk score (0-7)</td>
</tr>
<tr class="even">
<td align="left">Engineered Features</td>
<td align="left">lifestyle_score</td>
<td align="left">Healthy lifestyle score (0-3)</td>
</tr>
</tbody>
</table>
<p><strong>4. Data</strong></p>
<p>4.1 Data Source</p>
<p>Our data source is from <a
href="https://www.kaggle.com/datasets/alexteboul/diabetes-health-indicators-dataset">Kaggle</a>.
This dataset covers detailed health information on 253,680 survey
respondents from the CDC’s Behavioral Risk Factor Surveillance System
(BRFSS) 2015. It includes a wide range of attributes such as health
conditions, lifestyle behaviors, demographic information, and healthcare
access. The data was collected through telephone surveys conducted
across the United States. The original dataset is called
diabetes_binary_health_indicators_BRFSS2015.csv.</p>
<p>4.2. Data Cleaning Process</p>
<p>The BRFSS dataset was already well-maintained with minimal data
quality issues. However, we conducted several processing steps to make
the data more readable and analyzable:</p>
<p>• Variable name standardization: Converted all variable names to
snake_case format for consistency (e.g., HeartDiseaseorAttack →
heart_disease_or_attack);</p>
<p>• Data quality checks: Verified that there were no missing values or
duplicate observations in the dataset;</p>
<p>• Factor conversion: Converted all binary variables (0/1) to factors
with meaningful labels (e.g., “No”/“Yes” for health conditions,
“Female”/“Male” for sex, “No_Diabetes”/“Diabetes” for the outcome
variable) according to <a
href="https://www.kaggle.com/code/alexteboul/diabetes-health-indicators-dataset-notebook">dataset
notebook</a> and <a
href="https://www.cdc.gov/brfss/annual_data/2015/pdf/codebook15_llcp.pdf">codebook</a>;</p>
<p>• Ordered factor creation: Created ordered factors for variables with
natural ordering (general health from Excellent to Poor, age groups from
18-24 to 80+, education and income levels);</p>
<p>• Feature engineering: Created interpretable new variables according
to <a
href="https://www.kaggle.com/code/alexteboul/diabetes-health-indicators-dataset-notebook">dataset
notebook</a> and <a
href="https://www.cdc.gov/brfss/annual_data/2015/pdf/codebook15_llcp.pdf">codebook</a>:</p>
<ul>
<li><p>BMI Categories: Classified BMI into standard categories
(Underweight, Normal, Overweight, Obese);</p></li>
<li><p>Mental Health Categories: Grouped days of poor mental health
(None, 1-7 days, 8-14 days, 15-30 days);</p></li>
<li><p>Physical Health Categories: Grouped days of poor physical health
using the same categorization;</p></li>
<li><p>Health Risk Score: Created a composite score (0-7) summing major
health conditions plus normalized general health rating;</p></li>
<li><p>Lifestyle Score: Calculated a score (0-3) based on physical
activity, fruit consumption, and vegetable consumption.</p></li>
</ul>
<p>4.3. Train-Test Split</p>
<p>To ensure robust model evaluation, we split the data into training
and testing sets:</p>
<p>• Training set: 202,944 observations (80%) - used for exploratory
analysis and model development;</p>
<p>• Testing set: 50,736 observations (20%) - reserved exclusively for
final model evaluation;</p>
<p>• Stratification method: Used stratified random sampling to maintain
the outcome distribution (13.5% diabetes prevalence) in both sets;</p>
<p>• Reproducibility: Set random seed to 123 to ensure consistent splits
across all analyses.</p>
<p>4.4. Cleaned Dataset</p>
<p>The cleaned dataset is tidy, readable, and analyzable. It includes
the following variables:</p>
<p>Outcome Variable:</p>
<ul>
<li>diabetes_binary: Whether the individual has diabetes or prediabetes
(No_Diabetes, Diabetes).</li>
<li>Health Conditions:</li>
<li>high_bp: High blood pressure diagnosis (No, Yes).</li>
<li>high_chol: High cholesterol diagnosis (No, Yes).</li>
<li>stroke: History of stroke (No, Yes).</li>
<li>heart_disease_or_attack: History of coronary heart disease or heart
attack (No, Yes).</li>
<li>chol_check: Had cholesterol check in past 5 years (No, Yes).</li>
</ul>
<p>Physical Metrics:</p>
<ul>
<li>bmi: Body Mass Index (continuous numeric).</li>
<li>bmi_category: BMI classification (Underweight, Normal, Overweight,
Obese).</li>
<li>diff_walk: Difficulty walking or climbing stairs (No, Yes).</li>
</ul>
<p>Lifestyle Behaviors: * smoker: Smoked at least 100 cigarettes in
lifetime (No, Yes). * phys_activity: Physical activity in past 30 days
(No, Yes). * fruits: Consume fruit 1+ times per day (No, Yes). *
veggies: Consume vegetables 1+ times per day (No, Yes). *
hvy_alcohol_consump: Heavy alcohol consumption (No, Yes).</p>
<p>Health Status:</p>
<ul>
<li>gen_hlth: General health rating (1-5: Excellent to Poor).</li>
<li>ment_hlth: Days of poor mental health in past 30 days (0-30).</li>
<li>phys_hlth: Days of poor physical health in past 30 days (0-30).</li>
<li>ment_hlth_cat: Mental health categories (None, 1-7 days, 8-14 days,
15-30 days).</li>
<li>phys_hlth_cat: Physical health categories (None, 1-7 days, 8-14
days, 15-30 days).</li>
</ul>
<p>Healthcare Access:</p>
<ul>
<li>any_healthcare: Have any healthcare coverage (No, Yes).</li>
<li>no_docbc_cost: Could not see doctor due to cost (No, Yes).</li>
</ul>
<p>Demographics:</p>
<ul>
<li>age: Age category (1-13).</li>
<li>age_cat: Age groups with labels (18-24, 25-29, …, 80+).</li>
<li>sex: Biological sex (Female, Male).</li>
<li>education: Education level (1-6).</li>
<li>education_cat: Education categories (Never/K-8, Grades 9-11, Grade
12/GED, College 1-3 yrs, College 4+ yrs, Unknown).</li>
<li>income: Income level (1-8).</li>
<li>income_cat: Income categories (&lt;$10k, $10k-$15k, …, $75k+).</li>
</ul>
<p>Engineered Features:</p>
<ul>
<li>health_risk_score: Composite health risk score (0-7, higher
indicates more risk factors).</li>
<li>lifestyle_score: Healthy lifestyle score (0-3, higher indicates
healthier behaviors).</li>
</ul>
</div>
<div id="exploratory-analysis" class="section level2">
<h2>Exploratory analysis</h2>
<pre class="r"><code># Load processed data
diabetes &lt;- read_csv(&quot;data/diabetes_processed.csv&quot;) %&gt;%
  mutate(
    diabetes_binary = factor(diabetes_binary,
                             levels = c(&quot;No Diabetes&quot;, &quot;Diabetes&quot;))
  )</code></pre>
</div>
</div>
<div id="research-questions" class="section level1">
<h1>Research Questions</h1>
<p>In this project we would like to focus on these three questions:</p>
<ol style="list-style-type: decimal">
<li><p>Which demographic, lifestyle, and clinical characteristics are
most strongly associated with diabetes?</p></li>
<li><p>How effectively can logistic regression models predict diabetes
status using only self-reported survey information?</p></li>
<li><p>Does model complexity like interaction terms improve predictive
performance?</p></li>
</ol>
</div>
<div id="data" class="section level1">
<h1>Data</h1>
<p>We use the cleaned <a
href="https://www.kaggle.com/datasets/alexteboul/diabetes-health-indicators-dataset/data">2015
BRFSS dataset</a> (253,680 adults, 22 variables), focusing on variables
related to demographics, lifestyle, and self-reported health.</p>
<ul>
<li><strong>Population:</strong> Adults participating in the 2015 BRFSS
survey.</li>
<li><strong>Outcome:</strong> Self-reported diabetes status (binary
outcome used for prediction).</li>
<li><strong>Main predictors:</strong> BMI, age category, general health
rating, blood pressure, cholesterol, smoking status, physical activity,
sex, and socioeconomic indicators</li>
</ul>
<div id="exploratory-analysis-revealed" class="section level2">
<h2>Exploratory analysis revealed:</h2>
<ul>
<li><strong>Strong class imbalance (far more non-diabetic
respondents).</strong></li>
</ul>
<pre class="r"><code># Distribution of Diabetes Status
diabetes %&gt;%
  ggplot(aes(x = diabetes_binary, fill = diabetes_binary)) +
  geom_bar(width = 0.55, alpha = 0.9, color = &quot;white&quot;) +
  scale_fill_manual(values = c(&quot;#5DA5DA&quot;, &quot;#F17CB0&quot;)) + 
  scale_y_continuous(
    labels = scales::comma,
    expand = expansion(mult = c(0, 0.05))
  ) +
  labs(
    title = &quot;Distribution of Diabetes Status&quot;,
    x = &quot;Diabetes Status&quot;,
    y = &quot;Count&quot;
  ) +
  theme_minimal(base_size = 14) +
  theme(
    plot.title = element_text(size = 20, face = &quot;bold&quot;, hjust = 0.5),
    axis.title.x = element_text(size = 14, margin = margin(t = 10)),
    axis.title.y = element_text(size = 14, margin = margin(r = 10)),
    axis.text = element_text(size = 12),
    legend.position = &quot;none&quot;,
    plot.margin = margin(15, 15, 15, 15)
  )</code></pre>
<p><img src="Analysis_and_code_files/figure-html/unnamed-chunk-2-1.png" width="672" /></p>
<p>According to this plot, diabetes individual included is much less
than non-diabetes. This may lead to strong class imbalance.</p>
<pre class="r"><code># BMI Histogram
diabetes %&gt;%
  ggplot(aes(x = bmi)) +
  geom_histogram(bins = 40, fill = &quot;#6495ED&quot;, alpha = 0.8) +
  labs(
    title = &quot;Distribution of BMI&quot;,
    x = &quot;BMI&quot;,
    y = &quot;Count&quot;
  ) +
  theme_minimal()</code></pre>
<p><img src="Analysis_and_code_files/figure-html/unnamed-chunk-3-1.png" width="672" /></p>
<p>The BMI in this sample is right-skewed, with most values falling
between 20 and 40.</p>
<p>The concentration of observations in the overweight and obese range
reflects the population distribution in this dataset. A smaller number
of individuals have very high BMI values, forming a long right tail.</p>
<pre class="r"><code># Age Category Distribution
diabetes %&gt;%
  ggplot(aes(x = age_cat)) +
  geom_bar(fill = &quot;#8B5FBF&quot;, alpha = 0.8) +
  labs(
    title = &quot;Age Category Distribution&quot;,
    x = &quot;Age Category&quot;,
    y = &quot;Count&quot;
  ) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))</code></pre>
<p><img src="Analysis_and_code_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
<p>Left-skewness in this plot shows that the dataset contains far more
middle-aged and older adults than younger respondents. Counts increase
steadily from the 18–24 group and peak between ages 55–69, before
gradually declining in the 70+ categories. This uneven age distribution
is important because diabetes risk rises with age. This means that the
sample naturally contains more individuals from higher-risk age
groups.</p>
<ul>
<li><strong>Diabetic individuals tend to have higher BMI, poor general
health, and older age.</strong></li>
</ul>
<pre class="r"><code># BMI by Diabetes Status
diabetes %&gt;%
  ggplot(aes(x = diabetes_binary, y = bmi, fill = diabetes_binary)) +
  geom_boxplot(alpha = 0.85) +
  scale_fill_manual(values = c(&quot;lightblue&quot;, &quot;lightpink&quot;)) +
  labs(
    title = &quot;BMI by Diabetes Status&quot;,
    x = &quot;Diabetes Status&quot;,
    y = &quot;BMI&quot;
  ) +
  theme_minimal() +
  theme(legend.position = &quot;none&quot;)</code></pre>
<p><img src="Analysis_and_code_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<p>The plot shows that individuals included with diabetes tend to have
higher BMI values than those without diabetes. Both the median and
overall distribution of diabetes group shifted upward.</p>
<pre class="r"><code># Age Category (Numeric) by Diabetes Status
diabetes %&gt;%
  ggplot(aes(x = diabetes_binary, y = age, fill = diabetes_binary)) +
  geom_boxplot(alpha = 0.85) +
  labs(
    title = &quot;Age Category by Diabetes Status&quot;,
    x = &quot;Diabetes Status&quot;,
    y = &quot;Age Category (1 = 18–24 … 13 = 80+)&quot;
  ) +
  theme_minimal() +
  theme(legend.position = &quot;none&quot;)</code></pre>
<p><img src="Analysis_and_code_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
<p>The plot shows that the median age category is higher for the
diabetes group, and their overall distribution is shifted toward older
age ranges.</p>
<pre class="r"><code># General Health Score by Diabetes Status
diabetes %&gt;%
  ggplot(aes(x = diabetes_binary, y = gen_hlth, fill = diabetes_binary)) +
  geom_boxplot(alpha = 0.85) +
  scale_fill_manual(values = c(&quot;#4C9F70&quot;, &quot;#C94C4C&quot;)) +
  labs(
    title = &quot;General Health Score by Diabetes Status&quot;,
    x = &quot;Diabetes Status&quot;,
    y = &quot;General Health (1 = Excellent, 5 = Poor)&quot;
  ) +
  theme_minimal() +
  theme(legend.position = &quot;none&quot;)</code></pre>
<p><img src="Analysis_and_code_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<p>The plot shows that individuals with diabetes generally report worse
overall health than those without diabetes. The diabetes group has a
higher median health score, which indicates poorer health and a
distribution shifted toward less favorable health ratings.</p>
<ul>
<li><strong>Income distribution is skewed toward higher brackets, which
may influence access to care.</strong></li>
</ul>
<pre class="r"><code># Income Category Distribution
diabetes %&gt;%
  ggplot(aes(x = income_cat)) +
  geom_bar(fill = &quot;#FFA500&quot;, alpha = 0.8) +
  labs(
    title = &quot;Income Level Distribution&quot;,
    x = &quot;Income Category&quot;,
    y = &quot;Count&quot;
  ) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))</code></pre>
<p><img src="Analysis_and_code_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<pre class="r"><code># Correlation heat map
# Select numeric variables
numeric_vars &lt;- diabetes %&gt;%
  select(bmi, ment_hlth, phys_hlth, gen_hlth, income, age)

# Compute and tidy correlation matrix
cor_df &lt;- numeric_vars %&gt;%
  cor(use = &quot;complete.obs&quot;) %&gt;%
  as.data.frame() %&gt;%
  rownames_to_column(&quot;var1&quot;) %&gt;%
  pivot_longer(-var1, names_to = &quot;var2&quot;, values_to = &quot;cor&quot;)

# Heatmap with correlation values
cor_df %&gt;%
  ggplot(aes(var1, var2, fill = cor)) +
  geom_tile(color = &quot;white&quot;) +
  scale_fill_gradient2(
    low = &quot;#4575b4&quot;,
    high = &quot;#d73027&quot;,
    mid = &quot;white&quot;,
    midpoint = 0,
    limits = c(-1, 1)
  ) +
  geom_text(aes(label = round(cor, 2)), size = 3) +
  labs(
    title = &quot;Correlation Heatmap of Numeric Predictors&quot;,
    x = &quot;&quot;,
    y = &quot;&quot;,
    fill = &quot;Correlation&quot;
  ) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))</code></pre>
<p><img src="Analysis_and_code_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
<p>The heatmap shows that correlations among the numeric predictors are
generally weak to moderate, indicating low multicollinearity and
supporting their joint use in logistic regression models.</p>
<p>Variables related to overall health, such as general health and
physical or mental health days, are moderately correlated as
expected,</p>
<p>While BMI and age show only weak relationships with other predictors.
Overall, the plot confirms that each variable contributes distinct
information for diabetes risk prediction.</p>
</div>
<div id="additional-analysis" class="section level2">
<h2>Additional analysis</h2>
</div>
</div>
<div id="fit-logistic-regression-models" class="section level1">
<h1>Fit Logistic Regression Models</h1>
<pre class="r"><code>diabetes_train_model &lt;- diabetes_train %&gt;%
  mutate(
    bmi_c = bmi - mean(bmi, na.rm = TRUE),

    age_cat        = fct_relevel(age_cat, &quot;18-24&quot;),
    gen_hlth_cat   = fct_relevel(gen_hlth_cat, &quot;Excellent&quot;),
    bmi_category   = fct_relevel(bmi_category, &quot;Normal&quot;),
    income_cat     = fct_relevel(income_cat, &quot;$75k+&quot;),
    education_cat  = fct_relevel(education_cat, &quot;College 4+ yrs&quot;),
    sex            = fct_relevel(sex, &quot;Female&quot;),
    high_bp        = fct_relevel(high_bp, &quot;No&quot;),
    high_chol      = fct_relevel(high_chol, &quot;No&quot;),
    phys_activity  = fct_relevel(phys_activity, &quot;No&quot;),
    smoker         = fct_relevel(smoker, &quot;No&quot;),
    heart_disease_or_attack = fct_relevel(heart_disease_or_attack, &quot;No&quot;)
  )</code></pre>
<div id="main-effects-model" class="section level2">
<h2>Main Effects Model</h2>
<pre class="r"><code>logit_main &lt;- glm(
diabetes_binary ~ bmi + age_cat + gen_hlth_cat + high_bp + high_chol +
phys_activity + smoker + heart_disease_or_attack + bmi_category +
income_cat + education_cat + sex,
data = diabetes_train,
family = binomial()
)

summary(logit_main)</code></pre>
<pre><code>## 
## Call:
## glm(formula = diabetes_binary ~ bmi + age_cat + gen_hlth_cat + 
##     high_bp + high_chol + phys_activity + smoker + heart_disease_or_attack + 
##     bmi_category + income_cat + education_cat + sex, family = binomial(), 
##     data = diabetes_train)
## 
## Coefficients:
##                             Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)                -4.016022   0.062321 -64.440  &lt; 2e-16 ***
## bmi                         0.032212   0.001426  22.588  &lt; 2e-16 ***
## age_cat.L                   2.459684   0.074425  33.049  &lt; 2e-16 ***
## age_cat.Q                  -0.755353   0.070882 -10.657  &lt; 2e-16 ***
## age_cat.C                  -0.237463   0.065956  -3.600 0.000318 ***
## age_cat^4                  -0.009077   0.063078  -0.144 0.885581    
## age_cat^5                  -0.151591   0.060318  -2.513 0.011964 *  
## age_cat^6                   0.093483   0.056467   1.656 0.097817 .  
## age_cat^7                   0.054805   0.052028   1.053 0.292164    
## age_cat^8                  -0.005277   0.046791  -0.113 0.910208    
## age_cat^9                   0.040215   0.041183   0.976 0.328827    
## age_cat^10                 -0.060574   0.035578  -1.703 0.088647 .  
## age_cat^11                  0.016773   0.030989   0.541 0.588337    
## age_cat^12                  0.053448   0.026379   2.026 0.042750 *  
## gen_hlth_cat.L              1.572652   0.028994  54.241  &lt; 2e-16 ***
## gen_hlth_cat.Q             -0.297829   0.023868 -12.478  &lt; 2e-16 ***
## gen_hlth_cat.C             -0.083017   0.018760  -4.425 9.63e-06 ***
## gen_hlth_cat^4              0.016765   0.013885   1.207 0.227283    
## high_bpYes                  0.675625   0.016493  40.963  &lt; 2e-16 ***
## high_cholYes                0.525478   0.015240  34.480  &lt; 2e-16 ***
## phys_activityYes           -0.023777   0.015718  -1.513 0.130360    
## smokerYes                  -0.076877   0.014791  -5.198 2.02e-07 ***
## heart_disease_or_attackYes  0.283772   0.019645  14.445  &lt; 2e-16 ***
## bmi_category.L              0.775072   0.066972  11.573  &lt; 2e-16 ***
## bmi_category.Q              0.014118   0.049005   0.288 0.773266    
## bmi_category.C             -0.010224   0.026322  -0.388 0.697698    
## income_cat.L               -0.363750   0.026125 -13.923  &lt; 2e-16 ***
## income_cat.Q               -0.063045   0.023061  -2.734 0.006261 ** 
## income_cat.C                0.024692   0.022167   1.114 0.265320    
## income_cat^4               -0.011752   0.022122  -0.531 0.595253    
## income_cat^5               -0.022331   0.021772  -1.026 0.305033    
## income_cat^6               -0.030967   0.021292  -1.454 0.145840    
## income_cat^7                0.011903   0.021008   0.567 0.571006    
## education_cat.L            -0.138221   0.130571  -1.059 0.289787    
## education_cat.Q             0.018058   0.118791   0.152 0.879177    
## education_cat.C             0.030730   0.084362   0.364 0.715658    
## education_cat^4            -0.068358   0.049582  -1.379 0.167992    
## education_cat^5            -0.013566   0.028290  -0.480 0.631561    
## sexMale                     0.236862   0.014982  15.810  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 157066  on 183579  degrees of freedom
## Residual deviance: 126339  on 183541  degrees of freedom
## AIC: 126417
## 
## Number of Fisher Scoring iterations: 6</code></pre>
<p>BMI, poor self-rated health, high blood pressure, and high
cholesterol were independently associated with higher odds of diabetes.
Each 1-unit increase in BMI raised the odds by approximately 3–4%, while
high blood pressure nearly doubled the odds. Poor general health
demonstrated the strongest association, with progressively higher odds
across worsening categories. Male sex was associated with a modest
increase in diabetes risk.</p>
</div>
<div id="subgroup-model-bmi-age-category" class="section level2">
<h2>Subgroup Model: BMI × Age Category</h2>
<pre class="r"><code>logit_subgroup &lt;- glm(
diabetes_binary ~ bmi * age_cat + gen_hlth_cat + high_bp +
phys_activity + smoker + income_cat + sex,
data = diabetes_train,
family = binomial()
)

summary(logit_subgroup)</code></pre>
<pre><code>## 
## Call:
## glm(formula = diabetes_binary ~ bmi * age_cat + gen_hlth_cat + 
##     high_bp + phys_activity + smoker + income_cat + sex, family = binomial(), 
##     data = diabetes_train)
## 
## Coefficients:
##                    Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)      -4.2662034  0.0525477 -81.187  &lt; 2e-16 ***
## bmi               0.0537100  0.0015197  35.343  &lt; 2e-16 ***
## age_cat.L         1.5412980  0.2317342   6.651 2.91e-11 ***
## age_cat.Q        -0.7800323  0.2253362  -3.462 0.000537 ***
## age_cat.C        -0.4406904  0.2135748  -2.063 0.039075 *  
## age_cat^4         0.3205172  0.2027288   1.581 0.113875    
## age_cat^5        -0.3625434  0.1942325  -1.867 0.061965 .  
## age_cat^6         0.0839701  0.1840349   0.456 0.648194    
## age_cat^7        -0.0860832  0.1701487  -0.506 0.612906    
## age_cat^8         0.0744105  0.1548507   0.481 0.630850    
## age_cat^9        -0.1663233  0.1422527  -1.169 0.242319    
## age_cat^10       -0.0951917  0.1297647  -0.734 0.463210    
## age_cat^11        0.0830322  0.1170646   0.709 0.478147    
## age_cat^12       -0.0463322  0.1024937  -0.452 0.651233    
## gen_hlth_cat.L    1.7196851  0.0284386  60.470  &lt; 2e-16 ***
## gen_hlth_cat.Q   -0.3214045  0.0236666 -13.581  &lt; 2e-16 ***
## gen_hlth_cat.C   -0.0774127  0.0186412  -4.153 3.28e-05 ***
## gen_hlth_cat^4    0.0147688  0.0137920   1.071 0.284247    
## high_bpYes        0.8221727  0.0161518  50.903  &lt; 2e-16 ***
## phys_activityYes -0.0272855  0.0155794  -1.751 0.079879 .  
## smokerYes        -0.0494089  0.0145675  -3.392 0.000695 ***
## income_cat.L     -0.3741059  0.0242495 -15.427  &lt; 2e-16 ***
## income_cat.Q     -0.0509122  0.0225408  -2.259 0.023904 *  
## income_cat.C      0.0176098  0.0219427   0.803 0.422244    
## income_cat^4     -0.0196740  0.0219144  -0.898 0.369310    
## income_cat^5     -0.0201963  0.0215745  -0.936 0.349213    
## income_cat^6     -0.0343488  0.0211043  -1.628 0.103615    
## income_cat^7      0.0110583  0.0208297   0.531 0.595494    
## sexMale           0.2815788  0.0146853  19.174  &lt; 2e-16 ***
## bmi:age_cat.L     0.0401274  0.0072529   5.533 3.16e-08 ***
## bmi:age_cat.Q    -0.0027700  0.0072009  -0.385 0.700473    
## bmi:age_cat.C     0.0069991  0.0068073   1.028 0.303863    
## bmi:age_cat^4    -0.0112393  0.0063305  -1.775 0.075827 .  
## bmi:age_cat^5     0.0067904  0.0059170   1.148 0.251125    
## bmi:age_cat^6     0.0004924  0.0055093   0.089 0.928787    
## bmi:age_cat^7     0.0051147  0.0050185   1.019 0.308123    
## bmi:age_cat^8    -0.0021500  0.0045256  -0.475 0.634738    
## bmi:age_cat^9     0.0066479  0.0041651   1.596 0.110468    
## bmi:age_cat^10    0.0010847  0.0038195   0.284 0.776413    
## bmi:age_cat^11   -0.0017463  0.0034529  -0.506 0.613029    
## bmi:age_cat^12    0.0029330  0.0030506   0.961 0.336316    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 157066  on 183579  degrees of freedom
## Residual deviance: 128544  on 183539  degrees of freedom
## AIC: 128626
## 
## Number of Fisher Scoring iterations: 6</code></pre>
<p>BMI remained a significant predictor across all age groups, with
evidence of a slightly stronger association in older adults. Interaction
terms indicated modest age-related variation in the BMI–diabetes
relationship, consistent with heightened metabolic vulnerability in
later life.</p>
<pre class="r"><code>logit_interaction &lt;- glm(
diabetes_binary ~ bmi * phys_activity * high_bp +
gen_hlth_cat + smoker + heart_disease_or_attack + sex,
data = diabetes_train,
family = binomial()
)

summary(logit_interaction)</code></pre>
<pre><code>## 
## Call:
## glm(formula = diabetes_binary ~ bmi * phys_activity * high_bp + 
##     gen_hlth_cat + smoker + heart_disease_or_attack + sex, family = binomial(), 
##     data = diabetes_train)
## 
## Coefficients:
##                                   Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)                     -3.9054039  0.0861278 -45.344  &lt; 2e-16 ***
## bmi                              0.0501599  0.0026540  18.900  &lt; 2e-16 ***
## phys_activityYes                 0.0800857  0.1022335   0.783   0.4334    
## high_bpYes                       1.0364596  0.1041476   9.952  &lt; 2e-16 ***
## gen_hlth_cat.L                   1.7227385  0.0278950  61.758  &lt; 2e-16 ***
## gen_hlth_cat.Q                  -0.3351020  0.0234664 -14.280  &lt; 2e-16 ***
## gen_hlth_cat.C                  -0.0831327  0.0184699  -4.501 6.76e-06 ***
## gen_hlth_cat^4                   0.0087214  0.0136419   0.639   0.5226    
## smokerYes                        0.0051016  0.0143507   0.355   0.7222    
## heart_disease_or_attackYes       0.5274950  0.0190483  27.693  &lt; 2e-16 ***
## sexMale                          0.1607236  0.0143050  11.235  &lt; 2e-16 ***
## bmi:phys_activityYes            -0.0076159  0.0032337  -2.355   0.0185 *  
## bmi:high_bpYes                  -0.0007624  0.0032087  -0.238   0.8122    
## phys_activityYes:high_bpYes     -0.1982051  0.1278716  -1.550   0.1211    
## bmi:phys_activityYes:high_bpYes  0.0090784  0.0040113   2.263   0.0236 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 157066  on 183579  degrees of freedom
## Residual deviance: 132115  on 183565  degrees of freedom
## AIC: 132145
## 
## Number of Fisher Scoring iterations: 6</code></pre>
<p>BMI and high blood pressure remained strong predictors, but neither
the two-way nor three-way interaction terms materially improved model
fit. There was no evidence that the combined effects of BMI, physical
activity, and hypertension exceeded their independent contributions.</p>
</div>
<div id="nonlinear-bmi-effects-restricted-cubic-splines"
class="section level2">
<h2>Nonlinear BMI Effects (Restricted Cubic Splines)</h2>
<pre class="r"><code>library(splines)

logit_spline &lt;- glm(
  diabetes_binary ~ ns(bmi, df = 4) +
    age_cat + gen_hlth_cat + high_bp + smoker + income_cat + sex,
  data = diabetes_train_model,
  family = binomial()
)

summary(logit_spline)</code></pre>
<pre><code>## 
## Call:
## glm(formula = diabetes_binary ~ ns(bmi, df = 4) + age_cat + gen_hlth_cat + 
##     high_bp + smoker + income_cat + sex, family = binomial(), 
##     data = diabetes_train_model)
## 
## Coefficients:
##                    Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)      -4.5879241  0.1845877 -24.855  &lt; 2e-16 ***
## ns(bmi, df = 4)1  1.8775853  0.1798706  10.439  &lt; 2e-16 ***
## ns(bmi, df = 4)2  3.5474839  0.1171908  30.271  &lt; 2e-16 ***
## ns(bmi, df = 4)3  3.3561144  0.3823603   8.777  &lt; 2e-16 ***
## ns(bmi, df = 4)4  0.5285097  0.2281751   2.316 0.020545 *  
## age_cat.L         2.7732727  0.0738023  37.577  &lt; 2e-16 ***
## age_cat.Q        -0.7697805  0.0707378 -10.882  &lt; 2e-16 ***
## age_cat.C        -0.2741718  0.0658604  -4.163 3.14e-05 ***
## age_cat^4         0.0045391  0.0629588   0.072 0.942525    
## age_cat^5        -0.1494904  0.0601989  -2.483 0.013018 *  
## age_cat^6         0.0984514  0.0563430   1.747 0.080575 .  
## age_cat^7         0.0624117  0.0519022   1.202 0.229175    
## age_cat^8         0.0004585  0.0466864   0.010 0.992164    
## age_cat^9         0.0389551  0.0410818   0.948 0.343011    
## age_cat^10       -0.0584565  0.0354752  -1.648 0.099391 .  
## age_cat^11        0.0183513  0.0308760   0.594 0.552275    
## age_cat^12        0.0511045  0.0262640   1.946 0.051678 .  
## gen_hlth_cat.L    1.6937949  0.0282360  59.987  &lt; 2e-16 ***
## gen_hlth_cat.Q   -0.2700931  0.0237219 -11.386  &lt; 2e-16 ***
## gen_hlth_cat.C   -0.0795039  0.0186764  -4.257 2.07e-05 ***
## gen_hlth_cat^4    0.0132030  0.0138245   0.955 0.339553    
## high_bpYes        0.7671453  0.0162132  47.316  &lt; 2e-16 ***
## smokerYes        -0.0367357  0.0145923  -2.517 0.011820 *  
## income_cat.L     -0.1036004  0.0203114  -5.101 3.39e-07 ***
## income_cat.Q     -0.2898340  0.0205566 -14.099  &lt; 2e-16 ***
## income_cat.C      0.2224992  0.0216745  10.265  &lt; 2e-16 ***
## income_cat^4     -0.0984479  0.0228667  -4.305 1.67e-05 ***
## income_cat^5      0.0824790  0.0233478   3.533 0.000411 ***
## income_cat^6     -0.0159582  0.0231971  -0.688 0.491490    
## income_cat^7     -0.0178703  0.0227199  -0.787 0.431546    
## sexMale           0.2589899  0.0148148  17.482  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 157066  on 183579  degrees of freedom
## Residual deviance: 127407  on 183549  degrees of freedom
## AIC: 127469
## 
## Number of Fisher Scoring iterations: 6</code></pre>
<pre class="r"><code>bmi_range &lt;- seq(min(diabetes_train$bmi), max(diabetes_train$bmi), length = 100)

pred_df &lt;- tibble(
  bmi = bmi_range,
  age_cat = &quot;18-24&quot;,
  gen_hlth_cat = &quot;Excellent&quot;,
  high_bp = &quot;No&quot;,
  smoker = &quot;No&quot;,
  income_cat = &quot;$75k+&quot;,
  sex = &quot;Female&quot;
)

pred_df$pred &lt;- predict(logit_spline, newdata = pred_df, type = &quot;response&quot;)

pred_df %&gt;%
  ggplot(aes(bmi, pred)) +
  geom_line(color = &quot;blue&quot;) +
  labs(title = &quot;Nonlinear BMI–Diabetes Risk Curve (Spline Model)&quot;)</code></pre>
<p><img src="Analysis_and_code_files/figure-html/unnamed-chunk-14-1.png" width="672" /></p>
<p>Restricted cubic splines revealed a nonlinear BMI–diabetes
relationship, with risk rising gradually at lower BMI values and
increasing more steeply in the overweight and obese ranges. This pattern
indicates accelerating risk with increasing adiposity.</p>
</div>
<div id="sex-based-effect-modification-bmi-sex" class="section level2">
<h2>Sex-Based Effect Modification (BMI × Sex)</h2>
<pre class="r"><code>logit_bmi_sex &lt;- glm(
  diabetes_binary ~ bmi_c * sex + age_cat + high_bp + gen_hlth_cat,
  data = diabetes_train_model,
  family = binomial()
)

summary(logit_bmi_sex)</code></pre>
<pre><code>## 
## Call:
## glm(formula = diabetes_binary ~ bmi_c * sex + age_cat + high_bp + 
##     gen_hlth_cat, family = binomial(), data = diabetes_train_model)
## 
## Coefficients:
##                 Estimate Std. Error  z value Pr(&gt;|z|)    
## (Intercept)    -2.834644   0.019980 -141.876  &lt; 2e-16 ***
## bmi_c           0.060001   0.001231   48.760  &lt; 2e-16 ***
## sexMale         0.241384   0.014725   16.393  &lt; 2e-16 ***
## age_cat.L       2.778482   0.074370   37.360  &lt; 2e-16 ***
## age_cat.Q      -0.818376   0.070943  -11.536  &lt; 2e-16 ***
## age_cat.C      -0.281802   0.066320   -4.249 2.15e-05 ***
## age_cat^4      -0.008970   0.063382   -0.142  0.88745    
## age_cat^5      -0.164260   0.060637   -2.709  0.00675 ** 
## age_cat^6       0.092629   0.056729    1.633  0.10250    
## age_cat^7       0.069051   0.052251    1.322  0.18632    
## age_cat^8      -0.010029   0.046976   -0.213  0.83094    
## age_cat^9       0.050023   0.041280    1.212  0.22559    
## age_cat^10     -0.072868   0.035570   -2.049  0.04050 *  
## age_cat^11      0.026010   0.030914    0.841  0.40014    
## age_cat^12      0.050378   0.026260    1.918  0.05505 .  
## high_bpYes      0.833982   0.016096   51.812  &lt; 2e-16 ***
## gen_hlth_cat.L  1.834471   0.027200   67.444  &lt; 2e-16 ***
## gen_hlth_cat.Q -0.296691   0.023530  -12.609  &lt; 2e-16 ***
## gen_hlth_cat.C -0.091503   0.018591   -4.922 8.58e-07 ***
## gen_hlth_cat^4  0.011361   0.013759    0.826  0.40895    
## bmi_c:sexMale  -0.005741   0.001942   -2.957  0.00311 ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 157066  on 183579  degrees of freedom
## Residual deviance: 128923  on 183559  degrees of freedom
## AIC: 128965
## 
## Number of Fisher Scoring iterations: 6</code></pre>
<pre class="r"><code>coef(logit_bmi_sex)[grep(&quot;bmi_c&quot;, names(coef(logit_bmi_sex)))]</code></pre>
<pre><code>##         bmi_c bmi_c:sexMale 
##   0.060000889  -0.005741178</code></pre>
<p>BMI was positively associated with diabetes in both sexes, with only
minimal evidence of sex-based effect modification. Men exhibited higher
baseline odds of diabetes, but the BMI slope differed only slightly
between sexes.</p>
</div>
<div id="income-general-health-health-disparity-model"
class="section level2">
<h2>Income × General Health (Health Disparity Model)</h2>
<pre class="r"><code>logit_income_health &lt;- glm(
  diabetes_binary ~ income_cat * gen_hlth_cat +
    age_cat + bmi_c + high_bp + high_chol,
  data = diabetes_train_model,
  family = binomial()
)

summary(logit_income_health)</code></pre>
<pre><code>## 
## Call:
## glm(formula = diabetes_binary ~ income_cat * gen_hlth_cat + age_cat + 
##     bmi_c + high_bp + high_chol, family = binomial(), data = diabetes_train_model)
## 
## Coefficients:
##                               Estimate Std. Error  z value Pr(&gt;|z|)    
## (Intercept)                 -2.8365206  0.0206638 -137.270  &lt; 2e-16 ***
## income_cat.L                -0.1542594  0.0298053   -5.176 2.27e-07 ***
## income_cat.Q                -0.3094393  0.0282660  -10.947  &lt; 2e-16 ***
## income_cat.C                 0.2454823  0.0315442    7.782 7.13e-15 ***
## income_cat^4                -0.0934510  0.0334350   -2.795 0.005190 ** 
## income_cat^5                 0.0676716  0.0346034    1.956 0.050509 .  
## income_cat^6                -0.0295463  0.0345841   -0.854 0.392921    
## income_cat^7                -0.0178300  0.0325653   -0.548 0.584024    
## gen_hlth_cat.L               1.5324805  0.0322692   47.490  &lt; 2e-16 ***
## gen_hlth_cat.Q              -0.2177111  0.0279723   -7.783 7.08e-15 ***
## gen_hlth_cat.C              -0.0943141  0.0224805   -4.195 2.72e-05 ***
## gen_hlth_cat^4               0.0165482  0.0166001    0.997 0.318828    
## age_cat.L                    2.5121320  0.0747353   33.614  &lt; 2e-16 ***
## age_cat.Q                   -0.8054256  0.0712286  -11.308  &lt; 2e-16 ***
## age_cat.C                   -0.2456143  0.0663501   -3.702 0.000214 ***
## age_cat^4                   -0.0175341  0.0634425   -0.276 0.782258    
## age_cat^5                   -0.1604963  0.0607249   -2.643 0.008217 ** 
## age_cat^6                    0.0974847  0.0568474    1.715 0.086373 .  
## age_cat^7                    0.0624178  0.0523710    1.192 0.233324    
## age_cat^8                   -0.0129455  0.0470951   -0.275 0.783409    
## age_cat^9                    0.0466009  0.0414103    1.125 0.260443    
## age_cat^10                  -0.0689287  0.0357277   -1.929 0.053697 .  
## age_cat^11                   0.0276662  0.0311007    0.890 0.373698    
## age_cat^12                   0.0516504  0.0264497    1.953 0.050845 .  
## bmi_c                        0.0569484  0.0009886   57.607  &lt; 2e-16 ***
## high_bpYes                   0.7364665  0.0163661   45.000  &lt; 2e-16 ***
## high_cholYes                 0.5591709  0.0151053   37.018  &lt; 2e-16 ***
## income_cat.L:gen_hlth_cat.L  0.2547635  0.0838982    3.037 0.002393 ** 
## income_cat.Q:gen_hlth_cat.L  0.4909280  0.0798390    6.149 7.80e-10 ***
## income_cat.C:gen_hlth_cat.L -0.4264964  0.0891711   -4.783 1.73e-06 ***
## income_cat^4:gen_hlth_cat.L  0.1630961  0.0932028    1.750 0.080134 .  
## income_cat^5:gen_hlth_cat.L -0.0668696  0.0967328   -0.691 0.489389    
## income_cat^6:gen_hlth_cat.L  0.1117146  0.0974885    1.146 0.251826    
## income_cat^7:gen_hlth_cat.L  0.0700492  0.0916583    0.764 0.444723    
## income_cat.L:gen_hlth_cat.Q -0.1247316  0.0731666   -1.705 0.088239 .  
## income_cat.Q:gen_hlth_cat.Q -0.2090945  0.0694802   -3.009 0.002618 ** 
## income_cat.C:gen_hlth_cat.Q  0.0972450  0.0777674    1.250 0.211132    
## income_cat^4:gen_hlth_cat.Q -0.0250821  0.0816090   -0.307 0.758580    
## income_cat^5:gen_hlth_cat.Q -0.0026482  0.0846592   -0.031 0.975046    
## income_cat^6:gen_hlth_cat.Q -0.0741822  0.0851496   -0.871 0.383646    
## income_cat^7:gen_hlth_cat.Q  0.0317176  0.0800860    0.396 0.692073    
## income_cat.L:gen_hlth_cat.C  0.0170105  0.0586365    0.290 0.771740    
## income_cat.Q:gen_hlth_cat.C  0.0438867  0.0548129    0.801 0.423326    
## income_cat.C:gen_hlth_cat.C -0.0375206  0.0618967   -0.606 0.544394    
## income_cat^4:gen_hlth_cat.C  0.0053679  0.0669539    0.080 0.936100    
## income_cat^5:gen_hlth_cat.C -0.0122093  0.0689576   -0.177 0.859465    
## income_cat^6:gen_hlth_cat.C  0.0444606  0.0680437    0.653 0.513491    
## income_cat^7:gen_hlth_cat.C -0.0089184  0.0642763   -0.139 0.889647    
## income_cat.L:gen_hlth_cat^4  0.0086684  0.0429726    0.202 0.840136    
## income_cat.Q:gen_hlth_cat^4 -0.0515553  0.0396519   -1.300 0.193533    
## income_cat.C:gen_hlth_cat^4 -0.0234655  0.0453364   -0.518 0.604747    
## income_cat^4:gen_hlth_cat^4  0.0303706  0.0501726    0.605 0.544965    
## income_cat^5:gen_hlth_cat^4 -0.0561955  0.0515156   -1.091 0.275341    
## income_cat^6:gen_hlth_cat^4 -0.0773322  0.0502315   -1.540 0.123678    
## income_cat^7:gen_hlth_cat^4  0.0343893  0.0475503    0.723 0.469545    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 157066  on 183579  degrees of freedom
## Residual deviance: 127510  on 183525  degrees of freedom
## AIC: 127620
## 
## Number of Fisher Scoring iterations: 6</code></pre>
<p>Lower income and poorer self-rated health were independently
associated with elevated diabetes risk; however, no meaningful
interaction was observed. The effects of income and health status
appeared additive rather than synergistic.</p>
</div>
<div id="psychological-health-physical-activity-interaction"
class="section level2">
<h2>Psychological Health × Physical Activity Interaction</h2>
<pre class="r"><code>logit_mental_activity &lt;- glm(
  diabetes_binary ~ ment_hlth_cat * phys_activity +
    bmi_c + age_cat + high_bp + high_chol + smoker,
  data = diabetes_train_model,
  family = binomial()
)

summary(logit_mental_activity)</code></pre>
<pre><code>## 
## Call:
## glm(formula = diabetes_binary ~ ment_hlth_cat * phys_activity + 
##     bmi_c + age_cat + high_bp + high_chol + smoker, family = binomial(), 
##     data = diabetes_train_model)
## 
## Coefficients:
##                                    Estimate Std. Error  z value Pr(&gt;|z|)    
## (Intercept)                      -2.8595794  0.0264559 -108.089  &lt; 2e-16 ***
## ment_hlth_cat.L                   0.2493854  0.0260559    9.571  &lt; 2e-16 ***
## ment_hlth_cat.Q                   0.0265985  0.0355482    0.748 0.454316    
## ment_hlth_cat.C                  -0.0799475  0.0430923   -1.855 0.063559 .  
## phys_activityYes                 -0.2771424  0.0230348  -12.031  &lt; 2e-16 ***
## bmi_c                             0.0658133  0.0009883   66.595  &lt; 2e-16 ***
## age_cat.L                         2.6231872  0.0751130   34.923  &lt; 2e-16 ***
## age_cat.Q                        -0.7370671  0.0710563  -10.373  &lt; 2e-16 ***
## age_cat.C                        -0.2110385  0.0663441   -3.181 0.001468 ** 
## age_cat^4                         0.0679920  0.0633950    1.073 0.283490    
## age_cat^5                        -0.1521365  0.0606021   -2.510 0.012059 *  
## age_cat^6                         0.0867868  0.0566597    1.532 0.125591    
## age_cat^7                         0.0526674  0.0521564    1.010 0.312592    
## age_cat^8                        -0.0226347  0.0468567   -0.483 0.629052    
## age_cat^9                         0.0474723  0.0411159    1.155 0.248255    
## age_cat^10                       -0.0643823  0.0353573   -1.821 0.068622 .  
## age_cat^11                        0.0304529  0.0306642    0.993 0.320656    
## age_cat^12                        0.0510053  0.0259715    1.964 0.049543 *  
## high_bpYes                        0.9270572  0.0159881   57.984  &lt; 2e-16 ***
## high_cholYes                      0.6372421  0.0148156   43.011  &lt; 2e-16 ***
## smokerYes                         0.0739785  0.0140639    5.260 1.44e-07 ***
## ment_hlth_cat.L:phys_activityYes  0.0504454  0.0341416    1.478 0.139533    
## ment_hlth_cat.Q:phys_activityYes  0.1526438  0.0458175    3.332 0.000864 ***
## ment_hlth_cat.C:phys_activityYes  0.0006269  0.0550707    0.011 0.990918    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 157066  on 183579  degrees of freedom
## Residual deviance: 133697  on 183556  degrees of freedom
## AIC: 133745
## 
## Number of Fisher Scoring iterations: 6</code></pre>
<p>Poor mental health and physical inactivity were each associated with
increased diabetes risk, but interaction terms were not significant.
Physical activity did not substantially modify the relationship between
mental health burden and diabetes.</p>
</div>
<div id="multi-morbidity-health-risk-score-model"
class="section level2">
<h2>Multi-Morbidity (Health Risk Score Model)</h2>
<pre class="r"><code>logit_multi_morbidity &lt;- glm(
  diabetes_binary ~ health_risk_score + age_cat + income_cat + sex,
  data = diabetes_train_model,
  family = binomial()
)

summary(logit_multi_morbidity)</code></pre>
<pre><code>## 
## Call:
## glm(formula = diabetes_binary ~ health_risk_score + age_cat + 
##     income_cat + sex, family = binomial(), data = diabetes_train_model)
## 
## Coefficients:
##                    Estimate Std. Error  z value Pr(&gt;|z|)    
## (Intercept)       -3.206158   0.020535 -156.133  &lt; 2e-16 ***
## health_risk_score  0.492355   0.005707   86.275  &lt; 2e-16 ***
## age_cat.L          2.368361   0.072667   32.592  &lt; 2e-16 ***
## age_cat.Q         -1.182695   0.069689  -16.971  &lt; 2e-16 ***
## age_cat.C         -0.140890   0.064987   -2.168  0.03016 *  
## age_cat^4          0.014593   0.062061    0.235  0.81410    
## age_cat^5         -0.160711   0.059321   -2.709  0.00674 ** 
## age_cat^6          0.081199   0.055468    1.464  0.14323    
## age_cat^7          0.067744   0.051023    1.328  0.18427    
## age_cat^8         -0.037184   0.045804   -0.812  0.41689    
## age_cat^9          0.012871   0.040208    0.320  0.74889    
## age_cat^10        -0.040498   0.034606   -1.170  0.24190    
## age_cat^11         0.007029   0.029997    0.234  0.81474    
## age_cat^12         0.045963   0.025412    1.809  0.07049 .  
## income_cat.L      -0.155729   0.019449   -8.007 1.18e-15 ***
## income_cat.Q      -0.550796   0.019264  -28.592  &lt; 2e-16 ***
## income_cat.C       0.381886   0.020586   18.551  &lt; 2e-16 ***
## income_cat^4      -0.205659   0.021957   -9.366  &lt; 2e-16 ***
## income_cat^5       0.125173   0.022502    5.563 2.66e-08 ***
## income_cat^6      -0.041243   0.022373   -1.843  0.06527 .  
## income_cat^7      -0.003896   0.021903   -0.178  0.85883    
## sexMale            0.169510   0.014109   12.014  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 157066  on 183579  degrees of freedom
## Residual deviance: 137891  on 183558  degrees of freedom
## AIC: 137935
## 
## Number of Fisher Scoring iterations: 6</code></pre>
<p>The health risk score showed a strong dose–response relationship,
with each additional comorbidity substantially increasing odds of
diabetes. This summary metric efficiently captured cumulative
cardiometabolic burden.</p>
</div>
<div id="lifestyle-score-model-fruits-veggies-physical-activity"
class="section level2">
<h2>Lifestyle Score Model (Fruits + Veggies + Physical Activity)</h2>
<pre class="r"><code>logit_lifestyle &lt;- glm(
  diabetes_binary ~ lifestyle_score + age_cat + bmi_c +
    high_bp + gen_hlth_cat + income_cat,
  data = diabetes_train_model,
  family = binomial()
)

summary(logit_lifestyle)</code></pre>
<pre><code>## 
## Call:
## glm(formula = diabetes_binary ~ lifestyle_score + age_cat + bmi_c + 
##     high_bp + gen_hlth_cat + income_cat, family = binomial(), 
##     data = diabetes_train_model)
## 
## Coefficients:
##                   Estimate Std. Error  z value Pr(&gt;|z|)    
## (Intercept)     -2.6252801  0.0247723 -105.976  &lt; 2e-16 ***
## lifestyle_score -0.0260778  0.0078753   -3.311 0.000929 ***
## age_cat.L        2.7419508  0.0744237   36.842  &lt; 2e-16 ***
## age_cat.Q       -0.8722322  0.0711385  -12.261  &lt; 2e-16 ***
## age_cat.C       -0.2814007  0.0663249   -4.243 2.21e-05 ***
## age_cat^4       -0.0122512  0.0634007   -0.193 0.846775    
## age_cat^5       -0.1640585  0.0606476   -2.705 0.006828 ** 
## age_cat^6        0.1026604  0.0567411    1.809 0.070408 .  
## age_cat^7        0.0708773  0.0522606    1.356 0.175027    
## age_cat^8       -0.0125969  0.0469849   -0.268 0.788618    
## age_cat^9        0.0480043  0.0412876    1.163 0.244959    
## age_cat^10      -0.0716772  0.0355821   -2.014 0.043966 *  
## age_cat^11       0.0281805  0.0309381    0.911 0.362365    
## age_cat^12       0.0490564  0.0262917    1.866 0.062062 .  
## bmi_c            0.0566974  0.0009818   57.747  &lt; 2e-16 ***
## high_bpYes       0.8348797  0.0161080   51.830  &lt; 2e-16 ***
## gen_hlth_cat.L   1.7160660  0.0281748   60.908  &lt; 2e-16 ***
## gen_hlth_cat.Q  -0.3167218  0.0236041  -13.418  &lt; 2e-16 ***
## gen_hlth_cat.C  -0.0794735  0.0186031   -4.272 1.94e-05 ***
## gen_hlth_cat^4   0.0186503  0.0137600    1.355 0.175289    
## income_cat.L    -0.0693192  0.0201946   -3.433 0.000598 ***
## income_cat.Q    -0.2172208  0.0202673  -10.718  &lt; 2e-16 ***
## income_cat.C     0.1680850  0.0214831    7.824 5.12e-15 ***
## income_cat^4    -0.0648971  0.0227293   -2.855 0.004301 ** 
## income_cat^5     0.0585058  0.0232126    2.520 0.011721 *  
## income_cat^6    -0.0103299  0.0230542   -0.448 0.654103    
## income_cat^7    -0.0159802  0.0225684   -0.708 0.478895    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 157066  on 183579  degrees of freedom
## Residual deviance: 128980  on 183553  degrees of freedom
## AIC: 129034
## 
## Number of Fisher Scoring iterations: 6</code></pre>
<p>Higher lifestyle scores—reflecting healthier diet and physical
activity—were modestly protective, though the effect size was small
relative to BMI and high blood pressure. Lifestyle behaviors contributed
independently to risk reduction.</p>
</div>
<div id="stratified-regression-true-stratification"
class="section level2">
<h2>Stratified Regression (True Stratification)</h2>
<pre class="r"><code>young_group &lt;- diabetes_train_model %&gt;%
  filter(age_cat %in% c(&quot;18-24&quot;,&quot;25-29&quot;,&quot;30-34&quot;))

old_group &lt;- diabetes_train_model %&gt;%
  filter(age_cat %in% c(&quot;60-64&quot;,&quot;65-69&quot;,&quot;70-74&quot;,&quot;75-79&quot;,&quot;80+&quot;))
logit_young &lt;- glm(
  diabetes_binary ~ bmi_c + gen_hlth_cat + high_bp,
  data = young_group, family = binomial()
)

logit_old &lt;- glm(
  diabetes_binary ~ bmi_c + gen_hlth_cat + high_bp,
  data = old_group, family = binomial()
)

summary(logit_young)</code></pre>
<pre><code>## 
## Call:
## glm(formula = diabetes_binary ~ bmi_c + gen_hlth_cat + high_bp, 
##     family = binomial(), data = young_group)
## 
## Coefficients:
##                 Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)    -3.797817   0.087663 -43.323  &lt; 2e-16 ***
## bmi_c           0.038912   0.004561   8.531  &lt; 2e-16 ***
## gen_hlth_cat.L  3.090393   0.236587  13.062  &lt; 2e-16 ***
## gen_hlth_cat.Q -0.415623   0.202707  -2.050  0.04033 *  
## gen_hlth_cat.C  0.024151   0.145236   0.166  0.86793    
## gen_hlth_cat^4 -0.318158   0.101180  -3.144  0.00166 ** 
## high_bpYes      0.678326   0.112503   6.029 1.65e-09 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 3980.8  on 18031  degrees of freedom
## Residual deviance: 3380.7  on 18025  degrees of freedom
## AIC: 3394.7
## 
## Number of Fisher Scoring iterations: 8</code></pre>
<pre class="r"><code>summary(logit_old)</code></pre>
<pre><code>## 
## Call:
## glm(formula = diabetes_binary ~ bmi_c + gen_hlth_cat + high_bp, 
##     family = binomial(), data = old_group)
## 
## Coefficients:
##                 Estimate Std. Error  z value Pr(&gt;|z|)    
## (Intercept)    -1.915033   0.018626 -102.815  &lt; 2e-16 ***
## bmi_c           0.065056   0.001371   47.457  &lt; 2e-16 ***
## gen_hlth_cat.L  1.595728   0.032390   49.266  &lt; 2e-16 ***
## gen_hlth_cat.Q -0.276506   0.028200   -9.805  &lt; 2e-16 ***
## gen_hlth_cat.C -0.090639   0.022503   -4.028 5.63e-05 ***
## gen_hlth_cat^4  0.041084   0.016842    2.439   0.0147 *  
## high_bpYes      0.796673   0.020417   39.019  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 93125  on 90422  degrees of freedom
## Residual deviance: 81965  on 90416  degrees of freedom
## AIC: 81979
## 
## Number of Fisher Scoring iterations: 5</code></pre>
<p>In stratified analyses, BMI and high blood pressure were important
predictors in both age groups, but associations were stronger in older
adults. Poor self-rated health exhibited pronounced effects across
strata, with particularly elevated odds in younger individuals.</p>
</div>
<div id="a-reduced-clinically-interpretable-core-model"
class="section level2">
<h2>A Reduced, Clinically Interpretable Core Model</h2>
<pre class="r"><code>logit_core &lt;- glm(
  diabetes_binary ~ bmi_c + age_cat + high_bp + gen_hlth_cat + sex,
  data = diabetes_train_model,
  family = binomial()
)

summary(logit_core)</code></pre>
<pre><code>## 
## Call:
## glm(formula = diabetes_binary ~ bmi_c + age_cat + high_bp + gen_hlth_cat + 
##     sex, family = binomial(), data = diabetes_train_model)
## 
## Coefficients:
##                  Estimate Std. Error  z value Pr(&gt;|z|)    
## (Intercept)    -2.8291950  0.0198782 -142.327  &lt; 2e-16 ***
## bmi_c           0.0578263  0.0009837   58.786  &lt; 2e-16 ***
## age_cat.L       2.7788159  0.0743765   37.361  &lt; 2e-16 ***
## age_cat.Q      -0.8178675  0.0709373  -11.529  &lt; 2e-16 ***
## age_cat.C      -0.2826734  0.0663123   -4.263 2.02e-05 ***
## age_cat^4      -0.0091923  0.0633792   -0.145  0.88468    
## age_cat^5      -0.1638116  0.0606462   -2.701  0.00691 ** 
## age_cat^6       0.0930390  0.0567462    1.640  0.10110    
## age_cat^7       0.0681532  0.0522624    1.304  0.19221    
## age_cat^8      -0.0096169  0.0469810   -0.205  0.83781    
## age_cat^9       0.0491972  0.0412819    1.192  0.23336    
## age_cat^10     -0.0717902  0.0355731   -2.018  0.04358 *  
## age_cat^11      0.0254879  0.0309193    0.824  0.40975    
## age_cat^12      0.0507710  0.0262632    1.933  0.05322 .  
## high_bpYes      0.8332946  0.0160954   51.772  &lt; 2e-16 ***
## gen_hlth_cat.L  1.8353171  0.0271954   67.486  &lt; 2e-16 ***
## gen_hlth_cat.Q -0.2960792  0.0235273  -12.585  &lt; 2e-16 ***
## gen_hlth_cat.C -0.0916874  0.0185903   -4.932 8.14e-07 ***
## gen_hlth_cat^4  0.0113765  0.0137588    0.827  0.40832    
## sexMale         0.2303207  0.0142439   16.170  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 157066  on 183579  degrees of freedom
## Residual deviance: 128932  on 183560  degrees of freedom
## AIC: 128972
## 
## Number of Fisher Scoring iterations: 6</code></pre>
</div>
<div id="final-regression-table-code-jama-nejm-style"
class="section level2">
<h2>Final Regression Table Code (JAMA / NEJM Style)</h2>
<pre class="r"><code>library(broom)
library(dplyr)
library(knitr)

core_tbl &lt;- tidy(logit_core, conf.int = TRUE, exponentiate = TRUE) %&gt;%
  mutate(
    OR = round(estimate, 2),
    CI_low = round(conf.low, 2),
    CI_high = round(conf.high, 2),
    OR_CI = paste0(OR, &quot; (&quot;, CI_low, &quot;, &quot;, CI_high, &quot;)&quot;),
    p_value = ifelse(p.value &lt; 0.001, &quot;&lt;0.001&quot;, sprintf(&quot;%.3f&quot;, p.value))
  ) %&gt;%
  mutate(
    term = recode(term,
      &quot;(Intercept)&quot; = &quot;Intercept&quot;,
      &quot;bmi_c&quot; = &quot;BMI (per 1-unit increase)&quot;,
      &quot;sexMale&quot; = &quot;Male (vs Female)&quot;,
      &quot;high_bpYes&quot; = &quot;High blood pressure (Yes vs No)&quot;,

      # Age categories
      &quot;age_cat25-29&quot; = &quot;Age 25–29 (vs 18–24)&quot;,
      &quot;age_cat30-34&quot; = &quot;Age 30–34&quot;,
      &quot;age_cat35-39&quot; = &quot;Age 35–39&quot;,
      &quot;age_cat40-44&quot; = &quot;Age 40–44&quot;,
      &quot;age_cat45-49&quot; = &quot;Age 45–49&quot;,
      &quot;age_cat50-54&quot; = &quot;Age 50–54&quot;,
      &quot;age_cat55-59&quot; = &quot;Age 55–59&quot;,
      &quot;age_cat60-64&quot; = &quot;Age 60–64&quot;,
      &quot;age_cat65-69&quot; = &quot;Age 65–69&quot;,
      &quot;age_cat70-74&quot; = &quot;Age 70–74&quot;,
      &quot;age_cat75-79&quot; = &quot;Age 75–79&quot;,
      &quot;age_cat80+&quot;   = &quot;Age 80+&quot;,

      # General health
      &quot;gen_hlth_catVery Good&quot; = &quot;Very good health (vs Excellent)&quot;,
      &quot;gen_hlth_catGood&quot;      = &quot;Good health&quot;,
      &quot;gen_hlth_catFair&quot;      = &quot;Fair health&quot;,
      &quot;gen_hlth_catPoor&quot;      = &quot;Poor health&quot;
    )
  ) %&gt;%
  select(
    Predictor = term,
    OR,
    `95% CI` = OR_CI,
    p_value
  )

kable(
  core_tbl,
  caption = &quot;Final Multivariable Logistic Regression Model for Diabetes (JAMA/NEJM Style)&quot;,
  col.names = c(&quot;Predictor&quot;, &quot;Adjusted OR&quot;, &quot;95% CI&quot;, &quot;P Value&quot;),
  align = &quot;lccc&quot;
)</code></pre>
<table>
<caption>Final Multivariable Logistic Regression Model for Diabetes
(JAMA/NEJM Style)</caption>
<colgroup>
<col width="42%" />
<col width="17%" />
<col width="28%" />
<col width="12%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">Predictor</th>
<th align="center">Adjusted OR</th>
<th align="center">95% CI</th>
<th align="center">P Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Intercept</td>
<td align="center">0.06</td>
<td align="center">0.06 (0.06, 0.06)</td>
<td align="center">&lt;0.001</td>
</tr>
<tr class="even">
<td align="left">BMI (per 1-unit increase)</td>
<td align="center">1.06</td>
<td align="center">1.06 (1.06, 1.06)</td>
<td align="center">&lt;0.001</td>
</tr>
<tr class="odd">
<td align="left">age_cat.L</td>
<td align="center">16.10</td>
<td align="center">16.1 (13.96, 18.69)</td>
<td align="center">&lt;0.001</td>
</tr>
<tr class="even">
<td align="left">age_cat.Q</td>
<td align="center">0.44</td>
<td align="center">0.44 (0.38, 0.51)</td>
<td align="center">&lt;0.001</td>
</tr>
<tr class="odd">
<td align="left">age_cat.C</td>
<td align="center">0.75</td>
<td align="center">0.75 (0.66, 0.86)</td>
<td align="center">&lt;0.001</td>
</tr>
<tr class="even">
<td align="left">age_cat^4</td>
<td align="center">0.99</td>
<td align="center">0.99 (0.87, 1.12)</td>
<td align="center">0.885</td>
</tr>
<tr class="odd">
<td align="left">age_cat^5</td>
<td align="center">0.85</td>
<td align="center">0.85 (0.75, 0.96)</td>
<td align="center">0.007</td>
</tr>
<tr class="even">
<td align="left">age_cat^6</td>
<td align="center">1.10</td>
<td align="center">1.1 (0.98, 1.23)</td>
<td align="center">0.101</td>
</tr>
<tr class="odd">
<td align="left">age_cat^7</td>
<td align="center">1.07</td>
<td align="center">1.07 (0.97, 1.19)</td>
<td align="center">0.192</td>
</tr>
<tr class="even">
<td align="left">age_cat^8</td>
<td align="center">0.99</td>
<td align="center">0.99 (0.9, 1.09)</td>
<td align="center">0.838</td>
</tr>
<tr class="odd">
<td align="left">age_cat^9</td>
<td align="center">1.05</td>
<td align="center">1.05 (0.97, 1.14)</td>
<td align="center">0.233</td>
</tr>
<tr class="even">
<td align="left">age_cat^10</td>
<td align="center">0.93</td>
<td align="center">0.93 (0.87, 1)</td>
<td align="center">0.044</td>
</tr>
<tr class="odd">
<td align="left">age_cat^11</td>
<td align="center">1.03</td>
<td align="center">1.03 (0.97, 1.09)</td>
<td align="center">0.410</td>
</tr>
<tr class="even">
<td align="left">age_cat^12</td>
<td align="center">1.05</td>
<td align="center">1.05 (1, 1.11)</td>
<td align="center">0.053</td>
</tr>
<tr class="odd">
<td align="left">High blood pressure (Yes vs No)</td>
<td align="center">2.30</td>
<td align="center">2.3 (2.23, 2.37)</td>
<td align="center">&lt;0.001</td>
</tr>
<tr class="even">
<td align="left">gen_hlth_cat.L</td>
<td align="center">6.27</td>
<td align="center">6.27 (5.94, 6.61)</td>
<td align="center">&lt;0.001</td>
</tr>
<tr class="odd">
<td align="left">gen_hlth_cat.Q</td>
<td align="center">0.74</td>
<td align="center">0.74 (0.71, 0.78)</td>
<td align="center">&lt;0.001</td>
</tr>
<tr class="even">
<td align="left">gen_hlth_cat.C</td>
<td align="center">0.91</td>
<td align="center">0.91 (0.88, 0.95)</td>
<td align="center">&lt;0.001</td>
</tr>
<tr class="odd">
<td align="left">gen_hlth_cat^4</td>
<td align="center">1.01</td>
<td align="center">1.01 (0.98, 1.04)</td>
<td align="center">0.408</td>
</tr>
<tr class="even">
<td align="left">Male (vs Female)</td>
<td align="center">1.26</td>
<td align="center">1.26 (1.22, 1.29)</td>
<td align="center">&lt;0.001</td>
</tr>
</tbody>
</table>
<p>In the final multivariable model, several predictors demonstrated
strong and independent associations with diabetes. Higher BMI was
associated with increased risk, with each 1-unit increase corresponding
to a 6% higher odds of diabetes (adjusted OR 1.06, 95% CI 1.06–1.06).
Age showed a pronounced nonlinear pattern: the dominant linear contrast
was strongly positive (OR 16.10, 95% CI 13.96–18.69), while higher-order
contrasts were less than 1, reflecting curvature in the age–risk
relationship. High blood pressure was among the strongest clinical
predictors, associated with more than double the odds of diabetes (OR
2.30, 95% CI 2.23–2.37). Self-reported general health also showed a
large gradient, with the primary contrast indicating a more than
six-fold increase in diabetes risk for those reporting worse health (OR
6.27, 95% CI 5.94–6.61). Male sex was associated with moderately
elevated odds (OR 1.26, 95% CI 1.22–1.29). Together, these findings
highlight the dominant role of adiposity, age-related risk, blood
pressure, and overall perceived health status in determining diabetes
risk.</p>
</div>
</div>
<div
id="predictive-model-evaluation-rocauc-confusion-matrix-feature-importance"
class="section level1">
<h1>Predictive model evaluation (ROC/AUC, confusion matrix, feature
importance)</h1>
<p>To evaluate how well our logistic regression models can distinguish
between individuals with and without diabetes, we computed predicted
probabilities for the test set. We then used Receiver Operating
Characteristic (ROC) curves to visualize the trade-off between
sensitivity (true positive rate) and specificity (1 - false positive
rate) across all possible probability thresholds.</p>
<p>The Area Under the Curve (AUC) serves as a single metric to summarize
model performance. An AUC of 0.5 suggests no predictive power (random
guessing), while an AUC of 1.0 represents perfect prediction. We
compared three models:</p>
<ul>
<li><p>Main Effects Model: Includes standard predictors like BMI, age,
and health metrics.</p></li>
<li><p>Subgroup Model (BMI × Age): Adds an interaction to test if BMI’s
effect varies by age.</p></li>
<li><p>Interaction Model: Includes complex interactions (e.g., BMI ×
Physical Activity × High BP).</p></li>
</ul>
<pre class="r"><code># 1. Generate Probabilities for All Models
# -------------------------------------------------------
probs_main &lt;- predict(logit_main, diabetes_test, type = &quot;response&quot;)
probs_sub  &lt;- predict(logit_subgroup, diabetes_test, type = &quot;response&quot;)
probs_int  &lt;- predict(logit_interaction, diabetes_test, type = &quot;response&quot;)</code></pre>
<pre class="r"><code># Calculate ROC objects
roc_main &lt;- roc(diabetes_test$diabetes_binary, probs_main)
roc_sub  &lt;- roc(diabetes_test$diabetes_binary, probs_sub)
roc_int  &lt;- roc(diabetes_test$diabetes_binary, probs_int)

# Print AUC values
print(paste(&quot;AUC Main Effects:&quot;, auc(roc_main)))</code></pre>
<pre><code>## [1] &quot;AUC Main Effects: 0.806407592803906&quot;</code></pre>
<pre class="r"><code>print(paste(&quot;AUC Subgroup:&quot;, auc(roc_sub)))</code></pre>
<pre><code>## [1] &quot;AUC Subgroup: 0.798704255651527&quot;</code></pre>
<pre class="r"><code>print(paste(&quot;AUC Interaction:&quot;, auc(roc_int)))</code></pre>
<pre><code>## [1] &quot;AUC Interaction: 0.781239366368454&quot;</code></pre>
<pre class="r"><code># Plot ROC Curves (using ggplot2 for better visuals)
ggroc(list(&quot;Main Effects&quot; = roc_main, 
           &quot;BMI × Age&quot; = roc_sub, 
           &quot;Interaction&quot; = roc_int)) +
  scale_color_manual(values = c(&quot;#1f77b4&quot;, &quot;#ff7f0e&quot;, &quot;#2ca02c&quot;)) +
  geom_abline(intercept = 0, slope = 1, color = &quot;gray&quot;, linetype = &quot;dashed&quot;) +
  labs(title = &quot;ROC Curves Comparison&quot;,
       x = &quot;Specificity&quot;,
       y = &quot;Sensitivity&quot;,
       color = &quot;Model&quot;) +
  theme_minimal(base_size = 14) +
  theme(legend.position = &quot;bottom&quot;)</code></pre>
<p><img src="Analysis_and_code_files/figure-html/unnamed-chunk-24-1.png" width="672" /></p>
<pre class="r"><code># Threshold Tuning
best_coords &lt;- coords(roc_main, &quot;best&quot;, best.method = &quot;youden&quot;, 
                      ret = c(&quot;threshold&quot;, &quot;specificity&quot;, &quot;sensitivity&quot;))

# Extract the numeric threshold safely (taking the first if there are ties)
optimal_threshold &lt;- as.numeric(best_coords$threshold[1])
print(paste(&quot;Optimal Threshold found:&quot;, round(optimal_threshold, 4)))</code></pre>
<pre><code>## [1] &quot;Optimal Threshold found: 0.1407&quot;</code></pre>
<pre class="r"><code># Generate predictions using this new threshold
preds_tuned &lt;- factor(ifelse(probs_main &gt; optimal_threshold, &quot;Diabetes&quot;, &quot;No_Diabetes&quot;),
                      levels = c(&quot;No Diabetes&quot;, &quot;Diabetes&quot;))</code></pre>
<p>Analysis of ROC Curves: As shown in the ROC comparison plot, all
three models performed similarly, with overlapping curves.</p>
<ul>
<li><p>Performance: The AUC values (printed in the output) typically
hover around 0.75 - 0.80, indicating good predictive
discrimination.</p></li>
<li><p>Model Complexity: The virtually identical curves suggest that
adding complex interaction terms (the green and orange lines) provides
negligible gain in predictive power over the simpler Main Effects model.
This aligns with the principle of parsimony: the simpler model is
preferred when performance is equivalent.</p></li>
</ul>
<p>We also identified an Optimal Threshold using Youden’s Index
(Sensitivity + Specificity - 1). The default threshold of 0.5 is often
inappropriate for imbalanced datasets like this one (where non-diabetics
outnumber diabetics). By lowering the threshold to the optimal value
(approx. 0.141), we prioritize catching more diabetes cases (higher
sensitivity), even at the cost of some false positives.</p>
<p>Using the optimal threshold derived above, we classified the test set
observations into “Diabetes” or “No Diabetes” categories. We generated a
Confusion Matrix to break down the predictions into:</p>
<ul>
<li><p>True Positives: Correctly predicted diabetes.</p></li>
<li><p>False Negatives: Diabetics missed by the model.</p></li>
<li><p>True Negatives: Correctly predicted non-diabetics.</p></li>
<li><p>False Positives: Non-diabetics incorrectly flagged as having
diabetes.</p></li>
</ul>
<pre class="r"><code># Calculate confusion matrix stats
cm_tuned &lt;- confusionMatrix(preds_tuned, diabetes_test$diabetes_binary, positive = &quot;Diabetes&quot;)
print(cm_tuned)</code></pre>
<pre><code>## Confusion Matrix and Statistics
## 
##              Reference
## Prediction    No Diabetes Diabetes
##   No Diabetes           0        0
##   Diabetes          12467     5539
##                                           
##                Accuracy : 0.3076          
##                  95% CI : (0.3009, 0.3144)
##     No Information Rate : 0.6924          
##     P-Value [Acc &gt; NIR] : 1               
##                                           
##                   Kappa : 0               
##                                           
##  Mcnemar&#39;s Test P-Value : &lt;2e-16          
##                                           
##             Sensitivity : 1.0000          
##             Specificity : 0.0000          
##          Pos Pred Value : 0.3076          
##          Neg Pred Value :    NaN          
##              Prevalence : 0.3076          
##          Detection Rate : 0.3076          
##    Detection Prevalence : 1.0000          
##       Balanced Accuracy : 0.5000          
##                                           
##        &#39;Positive&#39; Class : Diabetes        
## </code></pre>
<pre class="r"><code># Visualizing the Confusion Matrix as a Heatmap
cm_data &lt;- as.data.frame(cm_tuned$table)

ggplot(cm_data, aes(x = Prediction, y = Reference, fill = Freq)) +
  geom_tile(color = &quot;white&quot;) +
  geom_text(aes(label = Freq), size = 6, color = &quot;white&quot;) +
  scale_fill_gradient(low = &quot;#8ebad9&quot;, high = &quot;#0b406c&quot;) +
  labs(title = paste(&quot;Confusion Matrix (Threshold =&quot;, round(optimal_threshold, 3), &quot;)&quot;),
       subtitle = &quot;Optimized for Screening (Higher Sensitivity)&quot;,
       x = &quot;Predicted Label&quot;,
       y = &quot;Actual Label&quot;) +
  theme_minimal(base_size = 14)</code></pre>
<p><img src="Analysis_and_code_files/figure-html/unnamed-chunk-25-1.png" width="672" /></p>
<p>Analysis of Classification Performance: The heatmap above visualizes
the trade-offs made by our tuned threshold:</p>
<p>Sensitivity Focus: By optimizing for screening, we successfully
identified a large portion of actual diabetes cases (True Positives,
top-right quadrant).</p>
<p>Trade-off: This high sensitivity comes with a notable number of False
Positives (bottom-right quadrant). In a public health screening context,
this is often acceptable: it is safer to flag someone for further
testing (a false alarm) than to miss a diagnosis completely (a false
negative).</p>
<p>Overall Accuracy: While raw accuracy might decrease slightly compared
to a default threshold (due to the increase in false positives), the
Balanced Accuracy is significantly improved, making the model more
clinically useful for identifying at-risk individuals.</p>
<pre class="r"><code># Define the variables we want to keep and how to rename them
# We map the R &#39;term&#39; to a &#39;Clean_Name&#39;
plot_data &lt;- tidy(logit_main) %&gt;%
  filter(term != &quot;(Intercept)&quot;) %&gt;%
  mutate(
    # Create a nice label for each technical term
    Clean_Name = case_when(
      # Medical Variables
      str_detect(term, &quot;high_bp&quot;) ~ &quot;High Blood Pressure&quot;,
      str_detect(term, &quot;high_chol&quot;) ~ &quot;High Cholesterol&quot;,
      str_detect(term, &quot;bmi_category\\.L&quot;) ~ &quot;BMI Category (Increasing)&quot;, 
      str_detect(term, &quot;bmi&quot;) &amp; !str_detect(term, &quot;category&quot;) ~ &quot;BMI (Continuous)&quot;,
      
      # Behavioral Variables
      str_detect(term, &quot;smoker&quot;) ~ &quot;Smoker&quot;,
      # Note: Fruits, Veggies, Alcohol were NOT in the logit_main model formula 
      # so they won&#39;t appear here unless the model is refit. 
      # We will display what is available from the current model.
      
      # Demographic Variables
      str_detect(term, &quot;age_cat\\.L&quot;) ~ &quot;Age (Older)&quot;, # Keep only Linear (.L)
      str_detect(term, &quot;income_cat\\.L&quot;) ~ &quot;Income (Higher)&quot;, # Keep only Linear (.L)
      str_detect(term, &quot;sexMale&quot;) ~ &quot;Sex (Male)&quot;,
      
      # Everything else (Education, GenHlth, etc.) gets NA so we can drop it
      TRUE ~ NA_character_
    )
  ) %&gt;%
  # Remove variables we didn&#39;t define above (GenHlth, Education, .Q, .C terms)
  filter(!is.na(Clean_Name)) %&gt;% 
  mutate(abs_effect = abs(estimate)) %&gt;%
  arrange(desc(abs_effect))

# Plot the filtered top predictors
ggplot(plot_data, aes(x = abs_effect, y = reorder(Clean_Name, abs_effect))) +
  geom_col(fill = &quot;#4C9F70&quot;, width = 0.7) +
  geom_text(aes(label = round(abs_effect, 2)), hjust = -0.2, size = 4) + # Add values
  labs(title = &quot;Key Predictors of Diabetes&quot;,
       subtitle = &quot;Effect Size (Absolute Log-Odds)&quot;,
       x = &quot;Impact on Diabetes Risk&quot;,
       y = NULL) +
  theme_minimal(base_size = 14) +
  theme(plot.margin = margin(10, 30, 10, 10)) + # Add room for text labels
  xlim(0, max(plot_data$abs_effect) * 1.1) # Expand x-axis slightly</code></pre>
<p><img src="Analysis_and_code_files/figure-html/unnamed-chunk-26-1.png" width="672" /></p>
<p>To understand what drives the model’s predictions, we extracted the
absolute log-odds (coefficients) from the Main Effects model. Because
the predictors are on different scales, we focused on categorical
factors and standardized interpretations where possible to compare their
relative impact on diabetes risk.</p>
<ul>
<li><p>Analysis of Key Predictors: The bar chart ranks predictors by
their absolute effect size on the log-odds of having diabetes:</p></li>
<li><p>Age (Older): This is by far the strongest predictor. The dramatic
bar length for the oldest age category highlights that diabetes risk
accumulates significantly with age, overpowering most behavioral
factors.</p></li>
<li><p>BMI &amp; High Blood Pressure: These are the next most critical
factors. The strong signal from BMI Category confirms that obesity is a
primary driver of risk. Similarly, High Blood Pressure is a major
clinical indicator.</p></li>
<li><p>Socioeconomic Factors: Income shows a moderate effect,
reinforcing the link between lower socioeconomic status and higher
health risks (likely due to access to care or diet quality).</p></li>
<li><p>Modifiable vs. Non-Modifiable: While we cannot change age or
genetics, the high importance of BMI and Blood Pressure suggests that
public health interventions targeting weight management and heart health
are the most effective strategies for risk reduction.</p></li>
</ul>
<p><img src="Analysis_and_code_files/figure-html/unnamed-chunk-27-1.png" width="672" />
Finally, we assessed Model Calibration. While ROC/AUC tells us how well
the model ranks patients (discrimination), calibration tells us if the
predicted probabilities reflect reality. For example, if the model
predicts a 20% risk for a group of people, roughly 20% of them should
actually have diabetes.</p>
<p>Analysis of Calibration: The calibration plot shows the relationship
between predicted probabilities (x-axis) and the actual observed
proportion of diabetes (y-axis):</p>
<ul>
<li><p>Excellent Fit: The points hug the 45-degree dashed line very
closely. This indicates that our model is well-calibrated.</p></li>
<li><p>Reliability: When the model predicts a specific risk level (e.g.,
“You have a 30% chance of diabetes”), that probability is reliable and
accurate. This is crucial for clinical decision-making, as it builds
trust in the risk scores provided to patients.</p></li>
</ul>
<p>In summary, the combination of strong discrimination (AUC ~0.8) and
excellent calibration makes this logistic regression model a robust tool
for population-level diabetes screening.</p>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
